// Code generated by ogen, DO NOT EDIT.

package realtek

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn1AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/Job/Get"

			if l := len("/Job/Get"); len(elem) >= l && elem[0:l] == "/Job/Get" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'A': // Prefix: "All"

				if l := len("All"); len(elem) >= l && elem[0:l] == "All" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'J': // Prefix: "JobList"

					if l := len("JobList"); len(elem) >= l && elem[0:l] == "JobList" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleListJobsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'L': // Prefix: "LocationList"

					if l := len("LocationList"); len(elem) >= l && elem[0:l] == "LocationList" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleListJobLocationsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'T': // Prefix: "TypeList"

					if l := len("TypeList"); len(elem) >= l && elem[0:l] == "TypeList" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleListJobTypesRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'F': // Prefix: "FilterList"

				if l := len("FilterList"); len(elem) >= l && elem[0:l] == "FilterList" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleFilterJobsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: rn1AllowedHeaders,
							acceptPost:     "application/x-www-form-urlencoded",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'V': // Prefix: "VacancyDetail"

				if l := len("VacancyDetail"); len(elem) >= l && elem[0:l] == "VacancyDetail" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetVacancyDetailRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [0]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/Job/Get"

			if l := len("/Job/Get"); len(elem) >= l && elem[0:l] == "/Job/Get" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'A': // Prefix: "All"

				if l := len("All"); len(elem) >= l && elem[0:l] == "All" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'J': // Prefix: "JobList"

					if l := len("JobList"); len(elem) >= l && elem[0:l] == "JobList" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ListJobsOperation
							r.summary = "Dump of open vacancies (no pagination; capped at 200 rows)."
							r.operationID = "listJobs"
							r.operationGroup = ""
							r.pathPattern = "/Job/GetAllJobList"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'L': // Prefix: "LocationList"

					if l := len("LocationList"); len(elem) >= l && elem[0:l] == "LocationList" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ListJobLocationsOperation
							r.summary = "Location list; GetFilterList takes the display name."
							r.operationID = "listJobLocations"
							r.operationGroup = ""
							r.pathPattern = "/Job/GetAllLocationList"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'T': // Prefix: "TypeList"

					if l := len("TypeList"); len(elem) >= l && elem[0:l] == "TypeList" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ListJobTypesOperation
							r.summary = "Job category list used to populate the job_type_id filter."
							r.operationID = "listJobTypes"
							r.operationGroup = ""
							r.pathPattern = "/Job/GetAllTypeList"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'F': // Prefix: "FilterList"

				if l := len("FilterList"); len(elem) >= l && elem[0:l] == "FilterList" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = FilterJobsOperation
						r.summary = "Server-side filtered vacancy list."
						r.operationID = "filterJobs"
						r.operationGroup = ""
						r.pathPattern = "/Job/GetFilterList"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'V': // Prefix: "VacancyDetail"

				if l := len("VacancyDetail"); len(elem) >= l && elem[0:l] == "VacancyDetail" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetVacancyDetailOperation
						r.summary = "Vacancy detail by JobOppId (not JobId)."
						r.operationID = "getVacancyDetail"
						r.operationGroup = ""
						r.pathPattern = "/Job/GetVacancyDetail"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			}

		}
	}
	return r, false
}
