// Code generated by ogen, DO NOT EDIT.

package realtek

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// GetVacancyDetailParams is parameters of getVacancyDetail operation.
type GetVacancyDetailParams struct {
	// The JobOppId from the job list (the id used in /Job/JobDetail?jobid= links).
	JobOppId string
}

func unpackGetVacancyDetailParams(packed middleware.Parameters) (params GetVacancyDetailParams) {
	{
		key := middleware.ParameterKey{
			Name: "JobOppId",
			In:   "query",
		}
		params.JobOppId = packed[key].(string)
	}
	return params
}

func decodeGetVacancyDetailParams(args [0]string, argsEscaped bool, r *http.Request) (params GetVacancyDetailParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: JobOppId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "JobOppId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.JobOppId = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "JobOppId",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
