// Code generated by ogen, DO NOT EDIT.

package job104

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetJobDetail implements getJobDetail operation.
	//
	// Fetches a single job by the code embedded in a search result's `link.job` URL (e.g.
	// `https://www.104.com.tw/job/624o1` → `624o1`).
	//
	// GET /job/ajax/content/{jobCode}
	GetJobDetail(ctx context.Context, params GetJobDetailParams) (*JobDetailResponse, error)
	// SearchJobs implements searchJobs operation.
	//
	// Searches jobs by keyword and/or filters. All parameters are optional; omit a parameter to leave that
	// dimension unfiltered.
	//
	// GET /jobs/search/api/jobs
	SearchJobs(ctx context.Context, params SearchJobsParams) (*JobsResponse, error)
	// NewError creates *ErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
