// Code generated by ogen, DO NOT EDIT.

package job104

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetJobDetail implements getJobDetail operation.
//
// Fetches a single job by the code embedded in a search result's `link.job` URL (e.g.
// `https://www.104.com.tw/job/624o1` → `624o1`).
//
// GET /job/ajax/content/{jobCode}
func (UnimplementedHandler) GetJobDetail(ctx context.Context, params GetJobDetailParams) (r *JobDetailResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchJobs implements searchJobs operation.
//
// Searches jobs by keyword and/or filters. All parameters are optional; omit a parameter to leave that
// dimension unfiltered.
//
// GET /jobs/search/api/jobs
func (UnimplementedHandler) SearchJobs(ctx context.Context, params SearchJobsParams) (r *JobsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
