// Code generated by ogen, DO NOT EDIT.

package bamboohr

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetJobDetail implements getJobDetail operation.
//
// Return one full posting.
//
// GET /careers/{id}/detail
func (UnimplementedHandler) GetJobDetail(ctx context.Context, params GetJobDetailParams) (r GetJobDetailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListJobs implements listJobs operation.
//
// Return every open posting's summary on the tenant's board.
//
// GET /careers/list
func (UnimplementedHandler) ListJobs(ctx context.Context) (r ListJobsRes, _ error) {
	return r, ht.ErrNotImplemented
}
