// Code generated by ogen, DO NOT EDIT.

package bamboohr

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetJobDetail implements getJobDetail operation.
	//
	// Return one full posting.
	//
	// GET /careers/{id}/detail
	GetJobDetail(ctx context.Context, params GetJobDetailParams) (GetJobDetailRes, error)
	// ListJobs implements listJobs operation.
	//
	// Return every open posting's summary on the tenant's board.
	//
	// GET /careers/list
	ListJobs(ctx context.Context) (ListJobsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
