// Code generated by ogen, DO NOT EDIT.

package bamboohr

import (
	"github.com/go-faster/jx"
)

// ATS-side location of a posting. Unlike the list feed's variant, it has `countryId` and no
// `province`; observed all-null on most postings.
// Ref: #/components/schemas/DetailAtsLocation
type DetailAtsLocation struct {
	Country   NilString `json:"country"`
	CountryId NilString `json:"countryId"`
	State     NilString `json:"state"`
	City      NilString `json:"city"`
}

// GetCountry returns the value of Country.
func (s *DetailAtsLocation) GetCountry() NilString {
	return s.Country
}

// GetCountryId returns the value of CountryId.
func (s *DetailAtsLocation) GetCountryId() NilString {
	return s.CountryId
}

// GetState returns the value of State.
func (s *DetailAtsLocation) GetState() NilString {
	return s.State
}

// GetCity returns the value of City.
func (s *DetailAtsLocation) GetCity() NilString {
	return s.City
}

// SetCountry sets the value of Country.
func (s *DetailAtsLocation) SetCountry(val NilString) {
	s.Country = val
}

// SetCountryId sets the value of CountryId.
func (s *DetailAtsLocation) SetCountryId(val NilString) {
	s.CountryId = val
}

// SetState sets the value of State.
func (s *DetailAtsLocation) SetState(val NilString) {
	s.State = val
}

// SetCity sets the value of City.
func (s *DetailAtsLocation) SetCity(val NilString) {
	s.City = val
}

// Structured location of a posting - a superset of the list feed's variant, adding postal code and
// country.
// Ref: #/components/schemas/DetailLocation
type DetailLocation struct {
	City           NilString `json:"city"`
	State          NilString `json:"state"`
	PostalCode     NilString `json:"postalCode"`
	AddressCountry NilString `json:"addressCountry"`
}

// GetCity returns the value of City.
func (s *DetailLocation) GetCity() NilString {
	return s.City
}

// GetState returns the value of State.
func (s *DetailLocation) GetState() NilString {
	return s.State
}

// GetPostalCode returns the value of PostalCode.
func (s *DetailLocation) GetPostalCode() NilString {
	return s.PostalCode
}

// GetAddressCountry returns the value of AddressCountry.
func (s *DetailLocation) GetAddressCountry() NilString {
	return s.AddressCountry
}

// SetCity sets the value of City.
func (s *DetailLocation) SetCity(val NilString) {
	s.City = val
}

// SetState sets the value of State.
func (s *DetailLocation) SetState(val NilString) {
	s.State = val
}

// SetPostalCode sets the value of PostalCode.
func (s *DetailLocation) SetPostalCode(val NilString) {
	s.PostalCode = val
}

// SetAddressCountry sets the value of AddressCountry.
func (s *DetailLocation) SetAddressCountry(val NilString) {
	s.AddressCountry = val
}

// Ref: #/components/schemas/DetailResponse
type DetailResponse struct {
	// Observed as an empty object.
	Meta   DetailResponseMeta `json:"meta"`
	Result DetailResult       `json:"result"`
}

// GetMeta returns the value of Meta.
func (s *DetailResponse) GetMeta() DetailResponseMeta {
	return s.Meta
}

// GetResult returns the value of Result.
func (s *DetailResponse) GetResult() DetailResult {
	return s.Result
}

// SetMeta sets the value of Meta.
func (s *DetailResponse) SetMeta(val DetailResponseMeta) {
	s.Meta = val
}

// SetResult sets the value of Result.
func (s *DetailResponse) SetResult(val DetailResult) {
	s.Result = val
}

func (*DetailResponse) getJobDetailRes() {}

// Observed as an empty object.
type DetailResponseMeta struct{}

// Ref: #/components/schemas/DetailResult
type DetailResult struct {
	JobOpening JobOpening `json:"jobOpening"`
	// Application-form field metadata (labels, required flags, select options) for the posting's apply
	// page. Not job data; surfaced as free-form JSON.
	FormFields OptDetailResultFormFields `json:"formFields"`
}

// GetJobOpening returns the value of JobOpening.
func (s *DetailResult) GetJobOpening() JobOpening {
	return s.JobOpening
}

// GetFormFields returns the value of FormFields.
func (s *DetailResult) GetFormFields() OptDetailResultFormFields {
	return s.FormFields
}

// SetJobOpening sets the value of JobOpening.
func (s *DetailResult) SetJobOpening(val JobOpening) {
	s.JobOpening = val
}

// SetFormFields sets the value of FormFields.
func (s *DetailResult) SetFormFields(val OptDetailResultFormFields) {
	s.FormFields = val
}

// Application-form field metadata (labels, required flags, select options) for the posting's apply
// page. Not job data; surfaced as free-form JSON.
type DetailResultFormFields map[string]jx.Raw

func (s *DetailResultFormFields) init() DetailResultFormFields {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// GetJobDetailFound is response for GetJobDetail operation.
type GetJobDetailFound struct{}

func (*GetJobDetailFound) getJobDetailRes() {}

// One full posting.
// Ref: #/components/schemas/JobOpening
type JobOpening struct {
	// Human-clickable posting page URL.
	JobOpeningShareUrl string `json:"jobOpeningShareUrl"`
	// Job title.
	JobOpeningName string `json:"jobOpeningName"`
	// Observed as "Open" on every published posting.
	JobOpeningStatus string `json:"jobOpeningStatus"`
	// Tenant-defined category id; null when uncategorized.
	JobCategoryId NilString `json:"jobCategoryId"`
	// Department id; null when the job has no department.
	DepartmentId NilString `json:"departmentId"`
	// Department display name. Observed as an empty string (not null) when the job has no department,
	// unlike the list feed's null.
	DepartmentLabel NilString `json:"departmentLabel"`
	// Tenant-defined employment type label, free-form; same domain as the list feed's field.
	EmploymentStatusLabel string            `json:"employmentStatusLabel"`
	Location              DetailLocation    `json:"location"`
	AtsLocation           DetailAtsLocation `json:"atsLocation"`
	// Full job description as HTML.
	Description string `json:"description"`
	// Free-form compensation text; null when the posting publishes none. Observed values range from
	// salaries to day rates, e.g. "$300 - $425/Day ($21.43 - $30.35 per hour)".
	Compensation NilString `json:"compensation"`
	// Posting date as YYYY-MM-DD. Kept a plain string since the surface is undocumented.
	DatePosted NilString `json:"datePosted"`
	// Experience level label; null when unset. Observed values are "Entry-level", "Mid-level", and
	// "Experienced".
	MinimumExperience NilString `json:"minimumExperience"`
	// Work mode as a numeric string: "0" on-site, "1" remote, "2" hybrid - same encoding as the list
	// feed's field.
	LocationType NilString `json:"locationType"`
	// Whether the posting is promoted on Seek. Observed only as false.
	SeekPromoted NilBool `json:"seekPromoted"`
}

// GetJobOpeningShareUrl returns the value of JobOpeningShareUrl.
func (s *JobOpening) GetJobOpeningShareUrl() string {
	return s.JobOpeningShareUrl
}

// GetJobOpeningName returns the value of JobOpeningName.
func (s *JobOpening) GetJobOpeningName() string {
	return s.JobOpeningName
}

// GetJobOpeningStatus returns the value of JobOpeningStatus.
func (s *JobOpening) GetJobOpeningStatus() string {
	return s.JobOpeningStatus
}

// GetJobCategoryId returns the value of JobCategoryId.
func (s *JobOpening) GetJobCategoryId() NilString {
	return s.JobCategoryId
}

// GetDepartmentId returns the value of DepartmentId.
func (s *JobOpening) GetDepartmentId() NilString {
	return s.DepartmentId
}

// GetDepartmentLabel returns the value of DepartmentLabel.
func (s *JobOpening) GetDepartmentLabel() NilString {
	return s.DepartmentLabel
}

// GetEmploymentStatusLabel returns the value of EmploymentStatusLabel.
func (s *JobOpening) GetEmploymentStatusLabel() string {
	return s.EmploymentStatusLabel
}

// GetLocation returns the value of Location.
func (s *JobOpening) GetLocation() DetailLocation {
	return s.Location
}

// GetAtsLocation returns the value of AtsLocation.
func (s *JobOpening) GetAtsLocation() DetailAtsLocation {
	return s.AtsLocation
}

// GetDescription returns the value of Description.
func (s *JobOpening) GetDescription() string {
	return s.Description
}

// GetCompensation returns the value of Compensation.
func (s *JobOpening) GetCompensation() NilString {
	return s.Compensation
}

// GetDatePosted returns the value of DatePosted.
func (s *JobOpening) GetDatePosted() NilString {
	return s.DatePosted
}

// GetMinimumExperience returns the value of MinimumExperience.
func (s *JobOpening) GetMinimumExperience() NilString {
	return s.MinimumExperience
}

// GetLocationType returns the value of LocationType.
func (s *JobOpening) GetLocationType() NilString {
	return s.LocationType
}

// GetSeekPromoted returns the value of SeekPromoted.
func (s *JobOpening) GetSeekPromoted() NilBool {
	return s.SeekPromoted
}

// SetJobOpeningShareUrl sets the value of JobOpeningShareUrl.
func (s *JobOpening) SetJobOpeningShareUrl(val string) {
	s.JobOpeningShareUrl = val
}

// SetJobOpeningName sets the value of JobOpeningName.
func (s *JobOpening) SetJobOpeningName(val string) {
	s.JobOpeningName = val
}

// SetJobOpeningStatus sets the value of JobOpeningStatus.
func (s *JobOpening) SetJobOpeningStatus(val string) {
	s.JobOpeningStatus = val
}

// SetJobCategoryId sets the value of JobCategoryId.
func (s *JobOpening) SetJobCategoryId(val NilString) {
	s.JobCategoryId = val
}

// SetDepartmentId sets the value of DepartmentId.
func (s *JobOpening) SetDepartmentId(val NilString) {
	s.DepartmentId = val
}

// SetDepartmentLabel sets the value of DepartmentLabel.
func (s *JobOpening) SetDepartmentLabel(val NilString) {
	s.DepartmentLabel = val
}

// SetEmploymentStatusLabel sets the value of EmploymentStatusLabel.
func (s *JobOpening) SetEmploymentStatusLabel(val string) {
	s.EmploymentStatusLabel = val
}

// SetLocation sets the value of Location.
func (s *JobOpening) SetLocation(val DetailLocation) {
	s.Location = val
}

// SetAtsLocation sets the value of AtsLocation.
func (s *JobOpening) SetAtsLocation(val DetailAtsLocation) {
	s.AtsLocation = val
}

// SetDescription sets the value of Description.
func (s *JobOpening) SetDescription(val string) {
	s.Description = val
}

// SetCompensation sets the value of Compensation.
func (s *JobOpening) SetCompensation(val NilString) {
	s.Compensation = val
}

// SetDatePosted sets the value of DatePosted.
func (s *JobOpening) SetDatePosted(val NilString) {
	s.DatePosted = val
}

// SetMinimumExperience sets the value of MinimumExperience.
func (s *JobOpening) SetMinimumExperience(val NilString) {
	s.MinimumExperience = val
}

// SetLocationType sets the value of LocationType.
func (s *JobOpening) SetLocationType(val NilString) {
	s.LocationType = val
}

// SetSeekPromoted sets the value of SeekPromoted.
func (s *JobOpening) SetSeekPromoted(val NilBool) {
	s.SeekPromoted = val
}

// ATS-side location of a list row. Carries the country when the board provides one (the sibling
// `location` never does); observed all-null on most rows. Unlike the detail endpoint's variant, it has
// `province` and no `countryId`.
// Ref: #/components/schemas/ListAtsLocation
type ListAtsLocation struct {
	Country  NilString `json:"country"`
	State    NilString `json:"state"`
	Province NilString `json:"province"`
	City     NilString `json:"city"`
}

// GetCountry returns the value of Country.
func (s *ListAtsLocation) GetCountry() NilString {
	return s.Country
}

// GetState returns the value of State.
func (s *ListAtsLocation) GetState() NilString {
	return s.State
}

// GetProvince returns the value of Province.
func (s *ListAtsLocation) GetProvince() NilString {
	return s.Province
}

// GetCity returns the value of City.
func (s *ListAtsLocation) GetCity() NilString {
	return s.City
}

// SetCountry sets the value of Country.
func (s *ListAtsLocation) SetCountry(val NilString) {
	s.Country = val
}

// SetState sets the value of State.
func (s *ListAtsLocation) SetState(val NilString) {
	s.State = val
}

// SetProvince sets the value of Province.
func (s *ListAtsLocation) SetProvince(val NilString) {
	s.Province = val
}

// SetCity sets the value of City.
func (s *ListAtsLocation) SetCity(val NilString) {
	s.City = val
}

// One posting summary. Sparse by design - no description, compensation, or posting date; those live
// only on the detail endpoint.
// Ref: #/components/schemas/ListJob
type ListJob struct {
	// Job opening id as a numeric string; pass it to the detail endpoint's path parameter unchanged.
	ID string `json:"id"`
	// Job title.
	JobOpeningName string `json:"jobOpeningName"`
	// Department id; null when the job has no department.
	DepartmentId NilString `json:"departmentId"`
	// Department display name; null when the job has no department (the detail endpoint reports an empty
	// string instead).
	DepartmentLabel NilString `json:"departmentLabel"`
	// Tenant-defined employment type label, free-form. Observed values include "Full-Time", "Full Time",
	// "Permanent Full-Time", "Contractor", "Independent Contractor", "Part-time Co-op", and "TBC".
	EmploymentStatusLabel string          `json:"employmentStatusLabel"`
	Location              ListLocation    `json:"location"`
	AtsLocation           ListAtsLocation `json:"atsLocation"`
	// Observed as null on every row of every surveyed board, including remote jobs - derive work mode from
	// `locationType` instead.
	IsRemote NilBool `json:"isRemote"`
	// Work mode as a numeric string: "0" on-site, "1" remote, "2" hybrid. Observed only in that domain but
	// not declared an enum, since the surface is undocumented.
	LocationType NilString `json:"locationType"`
}

// GetID returns the value of ID.
func (s *ListJob) GetID() string {
	return s.ID
}

// GetJobOpeningName returns the value of JobOpeningName.
func (s *ListJob) GetJobOpeningName() string {
	return s.JobOpeningName
}

// GetDepartmentId returns the value of DepartmentId.
func (s *ListJob) GetDepartmentId() NilString {
	return s.DepartmentId
}

// GetDepartmentLabel returns the value of DepartmentLabel.
func (s *ListJob) GetDepartmentLabel() NilString {
	return s.DepartmentLabel
}

// GetEmploymentStatusLabel returns the value of EmploymentStatusLabel.
func (s *ListJob) GetEmploymentStatusLabel() string {
	return s.EmploymentStatusLabel
}

// GetLocation returns the value of Location.
func (s *ListJob) GetLocation() ListLocation {
	return s.Location
}

// GetAtsLocation returns the value of AtsLocation.
func (s *ListJob) GetAtsLocation() ListAtsLocation {
	return s.AtsLocation
}

// GetIsRemote returns the value of IsRemote.
func (s *ListJob) GetIsRemote() NilBool {
	return s.IsRemote
}

// GetLocationType returns the value of LocationType.
func (s *ListJob) GetLocationType() NilString {
	return s.LocationType
}

// SetID sets the value of ID.
func (s *ListJob) SetID(val string) {
	s.ID = val
}

// SetJobOpeningName sets the value of JobOpeningName.
func (s *ListJob) SetJobOpeningName(val string) {
	s.JobOpeningName = val
}

// SetDepartmentId sets the value of DepartmentId.
func (s *ListJob) SetDepartmentId(val NilString) {
	s.DepartmentId = val
}

// SetDepartmentLabel sets the value of DepartmentLabel.
func (s *ListJob) SetDepartmentLabel(val NilString) {
	s.DepartmentLabel = val
}

// SetEmploymentStatusLabel sets the value of EmploymentStatusLabel.
func (s *ListJob) SetEmploymentStatusLabel(val string) {
	s.EmploymentStatusLabel = val
}

// SetLocation sets the value of Location.
func (s *ListJob) SetLocation(val ListLocation) {
	s.Location = val
}

// SetAtsLocation sets the value of AtsLocation.
func (s *ListJob) SetAtsLocation(val ListAtsLocation) {
	s.AtsLocation = val
}

// SetIsRemote sets the value of IsRemote.
func (s *ListJob) SetIsRemote(val NilBool) {
	s.IsRemote = val
}

// SetLocationType sets the value of LocationType.
func (s *ListJob) SetLocationType(val NilString) {
	s.LocationType = val
}

// ListJobsFound is response for ListJobs operation.
type ListJobsFound struct{}

func (*ListJobsFound) listJobsRes() {}

// Structured location of a list row.
// Ref: #/components/schemas/ListLocation
type ListLocation struct {
	City NilString `json:"city"`
	// State or province display name.
	State NilString `json:"state"`
}

// GetCity returns the value of City.
func (s *ListLocation) GetCity() NilString {
	return s.City
}

// GetState returns the value of State.
func (s *ListLocation) GetState() NilString {
	return s.State
}

// SetCity sets the value of City.
func (s *ListLocation) SetCity(val NilString) {
	s.City = val
}

// SetState sets the value of State.
func (s *ListLocation) SetState(val NilString) {
	s.State = val
}

// Ref: #/components/schemas/ListMeta
type ListMeta struct {
	// Number of rows in `result` (the feed is unpaginated).
	TotalCount int `json:"totalCount"`
}

// GetTotalCount returns the value of TotalCount.
func (s *ListMeta) GetTotalCount() int {
	return s.TotalCount
}

// SetTotalCount sets the value of TotalCount.
func (s *ListMeta) SetTotalCount(val int) {
	s.TotalCount = val
}

// Ref: #/components/schemas/ListResponse
type ListResponse struct {
	Meta ListMeta `json:"meta"`
	// Every open posting on the board, as sparse summaries.
	Result []ListJob `json:"result"`
}

// GetMeta returns the value of Meta.
func (s *ListResponse) GetMeta() ListMeta {
	return s.Meta
}

// GetResult returns the value of Result.
func (s *ListResponse) GetResult() []ListJob {
	return s.Result
}

// SetMeta sets the value of Meta.
func (s *ListResponse) SetMeta(val ListMeta) {
	s.Meta = val
}

// SetResult sets the value of Result.
func (s *ListResponse) SetResult(val []ListJob) {
	s.Result = val
}

func (*ListResponse) listJobsRes() {}

// NewNilBool returns new NilBool with value set to v.
func NewNilBool(v bool) NilBool {
	return NilBool{
		Value: v,
	}
}

// NilBool is nullable bool.
type NilBool struct {
	Value bool
	Null  bool
}

// SetTo sets value to v.
func (o *NilBool) SetTo(v bool) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilBool) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilBool) SetToNull() {
	o.Null = true
	var v bool
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilBool) Get() (v bool, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Structured error body returned for an unknown job id.
// Ref: #/components/schemas/NotFoundError
type NotFoundError struct {
	Type    string    `json:"type"`
	Title   string    `json:"title"`
	Details OptString `json:"details"`
	// Observed as an empty array.
	Meta []jx.Raw `json:"meta"`
}

// GetType returns the value of Type.
func (s *NotFoundError) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *NotFoundError) GetTitle() string {
	return s.Title
}

// GetDetails returns the value of Details.
func (s *NotFoundError) GetDetails() OptString {
	return s.Details
}

// GetMeta returns the value of Meta.
func (s *NotFoundError) GetMeta() []jx.Raw {
	return s.Meta
}

// SetType sets the value of Type.
func (s *NotFoundError) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *NotFoundError) SetTitle(val string) {
	s.Title = val
}

// SetDetails sets the value of Details.
func (s *NotFoundError) SetDetails(val OptString) {
	s.Details = val
}

// SetMeta sets the value of Meta.
func (s *NotFoundError) SetMeta(val []jx.Raw) {
	s.Meta = val
}

func (*NotFoundError) getJobDetailRes() {}

// NewOptDetailResultFormFields returns new OptDetailResultFormFields with value set to v.
func NewOptDetailResultFormFields(v DetailResultFormFields) OptDetailResultFormFields {
	return OptDetailResultFormFields{
		Value: v,
		Set:   true,
	}
}

// OptDetailResultFormFields is optional DetailResultFormFields.
type OptDetailResultFormFields struct {
	Value DetailResultFormFields
	Set   bool
}

// IsSet returns true if OptDetailResultFormFields was set.
func (o OptDetailResultFormFields) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDetailResultFormFields) Reset() {
	var v DetailResultFormFields
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDetailResultFormFields) SetTo(v DetailResultFormFields) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDetailResultFormFields) Get() (v DetailResultFormFields, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDetailResultFormFields) Or(d DetailResultFormFields) DetailResultFormFields {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
