// Code generated by ogen, DO NOT EDIT.

package bamboohr

// OperationName is the ogen operation name
type OperationName = string

const (
	GetJobDetailOperation OperationName = "GetJobDetail"
	ListJobsOperation     OperationName = "ListJobs"
)
