// Code generated by ogen, DO NOT EDIT.

package bamboohr

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"go.opentelemetry.io/otel/trace"
)

func encodeGetJobDetailResponse(response GetJobDetailRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *DetailResponse:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *GetJobDetailFound:
		w.WriteHeader(302)

		return nil

	case *NotFoundError:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(404)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeListJobsResponse(response ListJobsRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *ListResponse:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *ListJobsFound:
		w.WriteHeader(302)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}
