// Code generated by ogen, DO NOT EDIT.

package jobicy

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Echo of the query params the server actually applied.
// Ref: #/components/schemas/AppliedFilters
type AppliedFilters struct {
	Count    OptInt    `json:"count"`
	Geo      OptString `json:"geo"`
	Industry OptString `json:"industry"`
	Tag      OptString `json:"tag"`
	// Present on taxonomy responses.
	Get OptString `json:"get"`
}

// GetCount returns the value of Count.
func (s *AppliedFilters) GetCount() OptInt {
	return s.Count
}

// GetGeo returns the value of Geo.
func (s *AppliedFilters) GetGeo() OptString {
	return s.Geo
}

// GetIndustry returns the value of Industry.
func (s *AppliedFilters) GetIndustry() OptString {
	return s.Industry
}

// GetTag returns the value of Tag.
func (s *AppliedFilters) GetTag() OptString {
	return s.Tag
}

// GetGet returns the value of Get.
func (s *AppliedFilters) GetGet() OptString {
	return s.Get
}

// SetCount sets the value of Count.
func (s *AppliedFilters) SetCount(val OptInt) {
	s.Count = val
}

// SetGeo sets the value of Geo.
func (s *AppliedFilters) SetGeo(val OptString) {
	s.Geo = val
}

// SetIndustry sets the value of Industry.
func (s *AppliedFilters) SetIndustry(val OptString) {
	s.Industry = val
}

// SetTag sets the value of Tag.
func (s *AppliedFilters) SetTag(val OptString) {
	s.Tag = val
}

// SetGet sets the value of Get.
func (s *AppliedFilters) SetGet(val OptString) {
	s.Get = val
}

// Body of a 400 for an unknown `geo` or `industry` slug.
// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Success bool   `json:"success"`
	Error   string `json:"error"`
}

// GetSuccess returns the value of Success.
func (s *ErrorResponse) GetSuccess() bool {
	return s.Success
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetSuccess sets the value of Success.
func (s *ErrorResponse) SetSuccess(val bool) {
	s.Success = val
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

type GetRemoteJobsGet string

const (
	GetRemoteJobsGetLocations  GetRemoteJobsGet = "locations"
	GetRemoteJobsGetIndustries GetRemoteJobsGet = "industries"
)

// AllValues returns all GetRemoteJobsGet values.
func (GetRemoteJobsGet) AllValues() []GetRemoteJobsGet {
	return []GetRemoteJobsGet{
		GetRemoteJobsGetLocations,
		GetRemoteJobsGetIndustries,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetRemoteJobsGet) MarshalText() ([]byte, error) {
	switch s {
	case GetRemoteJobsGetLocations:
		return []byte(s), nil
	case GetRemoteJobsGetIndustries:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetRemoteJobsGet) UnmarshalText(data []byte) error {
	switch GetRemoteJobsGet(data) {
	case GetRemoteJobsGetLocations:
		*s = GetRemoteJobsGetLocations
		return nil
	case GetRemoteJobsGetIndustries:
		*s = GetRemoteJobsGetIndustries
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// GetRemoteJobsOK represents sum type.
type GetRemoteJobsOK struct {
	// Type selects the active sum variant, switch on this field.
	Type               GetRemoteJobsOKType
	JobsResponse       JobsResponse
	LocationsResponse  LocationsResponse
	IndustriesResponse IndustriesResponse
}

// GetRemoteJobsOKType is oneOf type of GetRemoteJobsOK.
type GetRemoteJobsOKType string

// Possible values for GetRemoteJobsOKType.
const (
	JobsResponseGetRemoteJobsOK       GetRemoteJobsOKType = "JobsResponse"
	LocationsResponseGetRemoteJobsOK  GetRemoteJobsOKType = "LocationsResponse"
	IndustriesResponseGetRemoteJobsOK GetRemoteJobsOKType = "IndustriesResponse"
)

// IsJobsResponse reports whether GetRemoteJobsOK is JobsResponse.
func (s GetRemoteJobsOK) IsJobsResponse() bool { return s.Type == JobsResponseGetRemoteJobsOK }

// IsLocationsResponse reports whether GetRemoteJobsOK is LocationsResponse.
func (s GetRemoteJobsOK) IsLocationsResponse() bool {
	return s.Type == LocationsResponseGetRemoteJobsOK
}

// IsIndustriesResponse reports whether GetRemoteJobsOK is IndustriesResponse.
func (s GetRemoteJobsOK) IsIndustriesResponse() bool {
	return s.Type == IndustriesResponseGetRemoteJobsOK
}

// SetJobsResponse sets GetRemoteJobsOK to JobsResponse.
func (s *GetRemoteJobsOK) SetJobsResponse(v JobsResponse) {
	s.Type = JobsResponseGetRemoteJobsOK
	s.JobsResponse = v
}

// GetJobsResponse returns JobsResponse and true boolean if GetRemoteJobsOK is JobsResponse.
func (s GetRemoteJobsOK) GetJobsResponse() (v JobsResponse, ok bool) {
	if !s.IsJobsResponse() {
		return v, false
	}
	return s.JobsResponse, true
}

// NewJobsResponseGetRemoteJobsOK returns new GetRemoteJobsOK from JobsResponse.
func NewJobsResponseGetRemoteJobsOK(v JobsResponse) GetRemoteJobsOK {
	var s GetRemoteJobsOK
	s.SetJobsResponse(v)
	return s
}

// SetLocationsResponse sets GetRemoteJobsOK to LocationsResponse.
func (s *GetRemoteJobsOK) SetLocationsResponse(v LocationsResponse) {
	s.Type = LocationsResponseGetRemoteJobsOK
	s.LocationsResponse = v
}

// GetLocationsResponse returns LocationsResponse and true boolean if GetRemoteJobsOK is LocationsResponse.
func (s GetRemoteJobsOK) GetLocationsResponse() (v LocationsResponse, ok bool) {
	if !s.IsLocationsResponse() {
		return v, false
	}
	return s.LocationsResponse, true
}

// NewLocationsResponseGetRemoteJobsOK returns new GetRemoteJobsOK from LocationsResponse.
func NewLocationsResponseGetRemoteJobsOK(v LocationsResponse) GetRemoteJobsOK {
	var s GetRemoteJobsOK
	s.SetLocationsResponse(v)
	return s
}

// SetIndustriesResponse sets GetRemoteJobsOK to IndustriesResponse.
func (s *GetRemoteJobsOK) SetIndustriesResponse(v IndustriesResponse) {
	s.Type = IndustriesResponseGetRemoteJobsOK
	s.IndustriesResponse = v
}

// GetIndustriesResponse returns IndustriesResponse and true boolean if GetRemoteJobsOK is IndustriesResponse.
func (s GetRemoteJobsOK) GetIndustriesResponse() (v IndustriesResponse, ok bool) {
	if !s.IsIndustriesResponse() {
		return v, false
	}
	return s.IndustriesResponse, true
}

// NewIndustriesResponseGetRemoteJobsOK returns new GetRemoteJobsOK from IndustriesResponse.
func NewIndustriesResponseGetRemoteJobsOK(v IndustriesResponse) GetRemoteJobsOK {
	var s GetRemoteJobsOK
	s.SetIndustriesResponse(v)
	return s
}

func (*GetRemoteJobsOK) getRemoteJobsRes() {}

// Ref: #/components/schemas/IndustriesResponse
type IndustriesResponse struct {
	Industries     []Industry        `json:"industries"`
	AppliedFilters OptAppliedFilters `json:"appliedFilters"`
}

// GetIndustries returns the value of Industries.
func (s *IndustriesResponse) GetIndustries() []Industry {
	return s.Industries
}

// GetAppliedFilters returns the value of AppliedFilters.
func (s *IndustriesResponse) GetAppliedFilters() OptAppliedFilters {
	return s.AppliedFilters
}

// SetIndustries sets the value of Industries.
func (s *IndustriesResponse) SetIndustries(val []Industry) {
	s.Industries = val
}

// SetAppliedFilters sets the value of AppliedFilters.
func (s *IndustriesResponse) SetAppliedFilters(val OptAppliedFilters) {
	s.AppliedFilters = val
}

// Ref: #/components/schemas/Industry
type Industry struct {
	IndustryID   int    `json:"industryID"`
	IndustryName string `json:"industryName"`
	// The value the `industry` search param accepts.
	IndustrySlug string `json:"industrySlug"`
}

// GetIndustryID returns the value of IndustryID.
func (s *Industry) GetIndustryID() int {
	return s.IndustryID
}

// GetIndustryName returns the value of IndustryName.
func (s *Industry) GetIndustryName() string {
	return s.IndustryName
}

// GetIndustrySlug returns the value of IndustrySlug.
func (s *Industry) GetIndustrySlug() string {
	return s.IndustrySlug
}

// SetIndustryID sets the value of IndustryID.
func (s *Industry) SetIndustryID(val int) {
	s.IndustryID = val
}

// SetIndustryName sets the value of IndustryName.
func (s *Industry) SetIndustryName(val string) {
	s.IndustryName = val
}

// SetIndustrySlug sets the value of IndustrySlug.
func (s *Industry) SetIndustrySlug(val string) {
	s.IndustrySlug = val
}

// One listing. `jobDescription` is the complete posting as HTML, so no separate detail fetch is
// needed. Display-name fields (`jobIndustry`, `jobType`) carry HTML entities (e.g. "DevOps &amp;
// Infrastructure").
// Ref: #/components/schemas/Job
type Job struct {
	ID int `json:"id"`
	// Public job page; per the usage terms, applicants must be sent here.
	URL         string `json:"url"`
	JobSlug     string `json:"jobSlug"`
	JobTitle    string `json:"jobTitle"`
	CompanyName string `json:"companyName"`
	// Logo image URL.
	CompanyLogo string `json:"companyLogo"`
	// Industry display names, not slugs.
	JobIndustry []string `json:"jobIndustry"`
	// Employment-type display names. Observed values: "Full-Time", "Part-Time", "Contract"; the vendor
	// docs also list internships.
	JobType []string `json:"jobType"`
	// Region display name, or "Anywhere".
	JobGeo string `json:"jobGeo"`
	// Seniority display name, or "Any". Observed values: "Any", "Entry-Level, Junior", "Midweight",
	// "Senior", "Director".
	JobLevel string `json:"jobLevel"`
	// Short plain-text preview of the description.
	JobExcerpt string `json:"jobExcerpt"`
	// Complete job posting as HTML.
	JobDescription string `json:"jobDescription"`
	// UTC publication timestamp.
	PubDate string `json:"pubDate"`
	// Present only when the posting states compensation; can appear without `salaryMax`.
	SalaryMin OptFloat64 `json:"salaryMin"`
	SalaryMax OptFloat64 `json:"salaryMax"`
	// ISO 4217 code.
	SalaryCurrency OptString `json:"salaryCurrency"`
	// Pay period, e.g. "yearly" or "hourly".
	SalaryPeriod OptString `json:"salaryPeriod"`
}

// GetID returns the value of ID.
func (s *Job) GetID() int {
	return s.ID
}

// GetURL returns the value of URL.
func (s *Job) GetURL() string {
	return s.URL
}

// GetJobSlug returns the value of JobSlug.
func (s *Job) GetJobSlug() string {
	return s.JobSlug
}

// GetJobTitle returns the value of JobTitle.
func (s *Job) GetJobTitle() string {
	return s.JobTitle
}

// GetCompanyName returns the value of CompanyName.
func (s *Job) GetCompanyName() string {
	return s.CompanyName
}

// GetCompanyLogo returns the value of CompanyLogo.
func (s *Job) GetCompanyLogo() string {
	return s.CompanyLogo
}

// GetJobIndustry returns the value of JobIndustry.
func (s *Job) GetJobIndustry() []string {
	return s.JobIndustry
}

// GetJobType returns the value of JobType.
func (s *Job) GetJobType() []string {
	return s.JobType
}

// GetJobGeo returns the value of JobGeo.
func (s *Job) GetJobGeo() string {
	return s.JobGeo
}

// GetJobLevel returns the value of JobLevel.
func (s *Job) GetJobLevel() string {
	return s.JobLevel
}

// GetJobExcerpt returns the value of JobExcerpt.
func (s *Job) GetJobExcerpt() string {
	return s.JobExcerpt
}

// GetJobDescription returns the value of JobDescription.
func (s *Job) GetJobDescription() string {
	return s.JobDescription
}

// GetPubDate returns the value of PubDate.
func (s *Job) GetPubDate() string {
	return s.PubDate
}

// GetSalaryMin returns the value of SalaryMin.
func (s *Job) GetSalaryMin() OptFloat64 {
	return s.SalaryMin
}

// GetSalaryMax returns the value of SalaryMax.
func (s *Job) GetSalaryMax() OptFloat64 {
	return s.SalaryMax
}

// GetSalaryCurrency returns the value of SalaryCurrency.
func (s *Job) GetSalaryCurrency() OptString {
	return s.SalaryCurrency
}

// GetSalaryPeriod returns the value of SalaryPeriod.
func (s *Job) GetSalaryPeriod() OptString {
	return s.SalaryPeriod
}

// SetID sets the value of ID.
func (s *Job) SetID(val int) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *Job) SetURL(val string) {
	s.URL = val
}

// SetJobSlug sets the value of JobSlug.
func (s *Job) SetJobSlug(val string) {
	s.JobSlug = val
}

// SetJobTitle sets the value of JobTitle.
func (s *Job) SetJobTitle(val string) {
	s.JobTitle = val
}

// SetCompanyName sets the value of CompanyName.
func (s *Job) SetCompanyName(val string) {
	s.CompanyName = val
}

// SetCompanyLogo sets the value of CompanyLogo.
func (s *Job) SetCompanyLogo(val string) {
	s.CompanyLogo = val
}

// SetJobIndustry sets the value of JobIndustry.
func (s *Job) SetJobIndustry(val []string) {
	s.JobIndustry = val
}

// SetJobType sets the value of JobType.
func (s *Job) SetJobType(val []string) {
	s.JobType = val
}

// SetJobGeo sets the value of JobGeo.
func (s *Job) SetJobGeo(val string) {
	s.JobGeo = val
}

// SetJobLevel sets the value of JobLevel.
func (s *Job) SetJobLevel(val string) {
	s.JobLevel = val
}

// SetJobExcerpt sets the value of JobExcerpt.
func (s *Job) SetJobExcerpt(val string) {
	s.JobExcerpt = val
}

// SetJobDescription sets the value of JobDescription.
func (s *Job) SetJobDescription(val string) {
	s.JobDescription = val
}

// SetPubDate sets the value of PubDate.
func (s *Job) SetPubDate(val string) {
	s.PubDate = val
}

// SetSalaryMin sets the value of SalaryMin.
func (s *Job) SetSalaryMin(val OptFloat64) {
	s.SalaryMin = val
}

// SetSalaryMax sets the value of SalaryMax.
func (s *Job) SetSalaryMax(val OptFloat64) {
	s.SalaryMax = val
}

// SetSalaryCurrency sets the value of SalaryCurrency.
func (s *Job) SetSalaryCurrency(val OptString) {
	s.SalaryCurrency = val
}

// SetSalaryPeriod sets the value of SalaryPeriod.
func (s *Job) SetSalaryPeriod(val OptString) {
	s.SalaryPeriod = val
}

// Ref: #/components/schemas/JobsResponse
type JobsResponse struct {
	ApiVersion       string `json:"apiVersion"`
	DocumentationUrl string `json:"documentationUrl"`
	// Attribution reminder from the feed.
	FriendlyNotice string `json:"friendlyNotice"`
	// Number of rows in `jobs`.
	JobCount int `json:"jobCount"`
	// UTC timestamp of the newest matching listing; empty string on zero-match (404) responses.
	LastUpdate     string         `json:"lastUpdate"`
	AppliedFilters AppliedFilters `json:"appliedFilters"`
	Jobs           []Job          `json:"jobs"`
	// True on 200; false on the zero-match 404 envelope.
	Success bool `json:"success"`
	// Only present on the zero-match 404 envelope.
	StatusCode OptInt `json:"statusCode"`
	// Only present on the zero-match 404 envelope.
	Message OptString `json:"message"`
}

// GetApiVersion returns the value of ApiVersion.
func (s *JobsResponse) GetApiVersion() string {
	return s.ApiVersion
}

// GetDocumentationUrl returns the value of DocumentationUrl.
func (s *JobsResponse) GetDocumentationUrl() string {
	return s.DocumentationUrl
}

// GetFriendlyNotice returns the value of FriendlyNotice.
func (s *JobsResponse) GetFriendlyNotice() string {
	return s.FriendlyNotice
}

// GetJobCount returns the value of JobCount.
func (s *JobsResponse) GetJobCount() int {
	return s.JobCount
}

// GetLastUpdate returns the value of LastUpdate.
func (s *JobsResponse) GetLastUpdate() string {
	return s.LastUpdate
}

// GetAppliedFilters returns the value of AppliedFilters.
func (s *JobsResponse) GetAppliedFilters() AppliedFilters {
	return s.AppliedFilters
}

// GetJobs returns the value of Jobs.
func (s *JobsResponse) GetJobs() []Job {
	return s.Jobs
}

// GetSuccess returns the value of Success.
func (s *JobsResponse) GetSuccess() bool {
	return s.Success
}

// GetStatusCode returns the value of StatusCode.
func (s *JobsResponse) GetStatusCode() OptInt {
	return s.StatusCode
}

// GetMessage returns the value of Message.
func (s *JobsResponse) GetMessage() OptString {
	return s.Message
}

// SetApiVersion sets the value of ApiVersion.
func (s *JobsResponse) SetApiVersion(val string) {
	s.ApiVersion = val
}

// SetDocumentationUrl sets the value of DocumentationUrl.
func (s *JobsResponse) SetDocumentationUrl(val string) {
	s.DocumentationUrl = val
}

// SetFriendlyNotice sets the value of FriendlyNotice.
func (s *JobsResponse) SetFriendlyNotice(val string) {
	s.FriendlyNotice = val
}

// SetJobCount sets the value of JobCount.
func (s *JobsResponse) SetJobCount(val int) {
	s.JobCount = val
}

// SetLastUpdate sets the value of LastUpdate.
func (s *JobsResponse) SetLastUpdate(val string) {
	s.LastUpdate = val
}

// SetAppliedFilters sets the value of AppliedFilters.
func (s *JobsResponse) SetAppliedFilters(val AppliedFilters) {
	s.AppliedFilters = val
}

// SetJobs sets the value of Jobs.
func (s *JobsResponse) SetJobs(val []Job) {
	s.Jobs = val
}

// SetSuccess sets the value of Success.
func (s *JobsResponse) SetSuccess(val bool) {
	s.Success = val
}

// SetStatusCode sets the value of StatusCode.
func (s *JobsResponse) SetStatusCode(val OptInt) {
	s.StatusCode = val
}

// SetMessage sets the value of Message.
func (s *JobsResponse) SetMessage(val OptString) {
	s.Message = val
}

func (*JobsResponse) getRemoteJobsRes() {}

// Ref: #/components/schemas/Location
type Location struct {
	GeoID   int    `json:"geoID"`
	GeoName string `json:"geoName"`
	// The value the `geo` search param accepts.
	GeoSlug string `json:"geoSlug"`
}

// GetGeoID returns the value of GeoID.
func (s *Location) GetGeoID() int {
	return s.GeoID
}

// GetGeoName returns the value of GeoName.
func (s *Location) GetGeoName() string {
	return s.GeoName
}

// GetGeoSlug returns the value of GeoSlug.
func (s *Location) GetGeoSlug() string {
	return s.GeoSlug
}

// SetGeoID sets the value of GeoID.
func (s *Location) SetGeoID(val int) {
	s.GeoID = val
}

// SetGeoName sets the value of GeoName.
func (s *Location) SetGeoName(val string) {
	s.GeoName = val
}

// SetGeoSlug sets the value of GeoSlug.
func (s *Location) SetGeoSlug(val string) {
	s.GeoSlug = val
}

// Ref: #/components/schemas/LocationsResponse
type LocationsResponse struct {
	Locations      []Location        `json:"locations"`
	AppliedFilters OptAppliedFilters `json:"appliedFilters"`
}

// GetLocations returns the value of Locations.
func (s *LocationsResponse) GetLocations() []Location {
	return s.Locations
}

// GetAppliedFilters returns the value of AppliedFilters.
func (s *LocationsResponse) GetAppliedFilters() OptAppliedFilters {
	return s.AppliedFilters
}

// SetLocations sets the value of Locations.
func (s *LocationsResponse) SetLocations(val []Location) {
	s.Locations = val
}

// SetAppliedFilters sets the value of AppliedFilters.
func (s *LocationsResponse) SetAppliedFilters(val OptAppliedFilters) {
	s.AppliedFilters = val
}

// NewOptAppliedFilters returns new OptAppliedFilters with value set to v.
func NewOptAppliedFilters(v AppliedFilters) OptAppliedFilters {
	return OptAppliedFilters{
		Value: v,
		Set:   true,
	}
}

// OptAppliedFilters is optional AppliedFilters.
type OptAppliedFilters struct {
	Value AppliedFilters
	Set   bool
}

// IsSet returns true if OptAppliedFilters was set.
func (o OptAppliedFilters) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAppliedFilters) Reset() {
	var v AppliedFilters
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAppliedFilters) SetTo(v AppliedFilters) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAppliedFilters) Get() (v AppliedFilters, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAppliedFilters) Or(d AppliedFilters) AppliedFilters {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGetRemoteJobsGet returns new OptGetRemoteJobsGet with value set to v.
func NewOptGetRemoteJobsGet(v GetRemoteJobsGet) OptGetRemoteJobsGet {
	return OptGetRemoteJobsGet{
		Value: v,
		Set:   true,
	}
}

// OptGetRemoteJobsGet is optional GetRemoteJobsGet.
type OptGetRemoteJobsGet struct {
	Value GetRemoteJobsGet
	Set   bool
}

// IsSet returns true if OptGetRemoteJobsGet was set.
func (o OptGetRemoteJobsGet) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGetRemoteJobsGet) Reset() {
	var v GetRemoteJobsGet
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGetRemoteJobsGet) SetTo(v GetRemoteJobsGet) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGetRemoteJobsGet) Get() (v GetRemoteJobsGet, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGetRemoteJobsGet) Or(d GetRemoteJobsGet) GetRemoteJobsGet {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
