// Code generated by ogen, DO NOT EDIT.

package jobicy

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetRemoteJobs implements getRemoteJobs operation.
	//
	// Without `get`, returns the latest remote jobs matching the search params, newest first. With `get`,
	// returns the requested taxonomy (the valid `geo` or `industry` slugs) and ignores the search params.
	// Zero-match searches are HTTP 404, but the body still carries the normal jobs envelope with an empty
	// `jobs` array plus `statusCode`/`message` trailer fields — treat it as an empty result, not an
	// error. An unknown `geo`/`industry` slug is HTTP 400 with a small
	// `{"success": false, "error": "..."}` body.
	//
	// GET /api/v2/remote-jobs
	GetRemoteJobs(ctx context.Context, params GetRemoteJobsParams) (GetRemoteJobsRes, error)
	// NewError creates *ErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
