// Code generated by ogen, DO NOT EDIT.

package jobicy

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetRemoteJobs implements getRemoteJobs operation.
//
// Without `get`, returns the latest remote jobs matching the search params, newest first. With `get`,
// returns the requested taxonomy (the valid `geo` or `industry` slugs) and ignores the search params.
// Zero-match searches are HTTP 404, but the body still carries the normal jobs envelope with an empty
// `jobs` array plus `statusCode`/`message` trailer fields — treat it as an empty result, not an
// error. An unknown `geo`/`industry` slug is HTTP 400 with a small
// `{"success": false, "error": "..."}` body.
//
// GET /api/v2/remote-jobs
func (UnimplementedHandler) GetRemoteJobs(ctx context.Context, params GetRemoteJobsParams) (r GetRemoteJobsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
