// Code generated by ogen, DO NOT EDIT.

package quanta

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ListJobs implements listJobs operation.
	//
	// Returns the whole board in one response. The query string is ignored (byte-identical bodies observed
	// for keyword/category/ limit probes), so search, category, location, and detail narrowing all happen
	// client-side.
	//
	// GET /QuantaRecruit/Home/QueryJob
	ListJobs(ctx context.Context) (*JobList, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
