// Code generated by ogen, DO NOT EDIT.

package quanta

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ListJobs implements listJobs operation.
//
// Returns the whole board in one response. The query string is ignored (byte-identical bodies observed
// for keyword/category/ limit probes), so search, category, location, and detail narrowing all happen
// client-side.
//
// GET /QuantaRecruit/Home/QueryJob
func (UnimplementedHandler) ListJobs(ctx context.Context) (r *JobList, _ error) {
	return r, ht.ErrNotImplemented
}
