// Code generated by ogen, DO NOT EDIT.

package quanta

// Ref: #/components/schemas/Job
type Job struct {
	// Human-facing job code, e.g. "J0106".
	JobCode string `json:"jobdid"`
	// Unique per-vacancy id; the site's share links use it as `?serial=`. Detail lookup means finding this
	// id in the dump.
	Serial string `json:"serial"`
	// Job category id; paired with `caponm`.
	CategoryID string `json:"capoid"`
	// Job category display name (e.g. 硬體研發).
	CategoryName string `json:"caponm"`
	// Internal category grouping id; distinct from `capoid` and unused by the site's front-end JS.
	CataID string `json:"cataid"`
	// Job title.
	Title string `json:"jobdnm"`
	// Work location id; paired with `locatm`.
	LocationID string `json:"locati"`
	// Work location display name (e.g. 林口研發中心).
	LocationName string `json:"locatm"`
	// Posted on the external board, Y/N — only "Y" observed; the dump contains only externally posted
	// vacancies.
	PostedExternal string `json:"posext"`
	// Also posted on the internal board, Y/N.
	PostedInternal string `json:"posint"`
	// Cancellation flag, Y/N — only "N" observed; the dump contains only active vacancies.
	Cancelled string `json:"cancel"`
	// Y/N flag of unobserved semantics; "N" appeared on exactly one row at capture time.
	IsCont string `json:"iscont"`
	// Qualification requirements, plain text with CRLF newlines. Null (or empty) on a few rows.
	Requirements NilString `json:"requnm"`
	// Job description, plain text with CRLF newlines.
	Description string `json:"descnm"`
	// Comma-separated hashtags; may be empty, and values may carry a leading space.
	Keywords string `json:"keywrd"`
	// Hot-job ordering: "0" means not hot; any other value marks the row as 熱門職缺 and sorts the hot
	// list.
	HotOrder string `json:"ordern"`
	// Salary text (e.g. 面議...); may be empty.
	Salary string `json:"salary"`
	// Recently-posted flag, Y/N; the site currently renders no badge for it.
	NewJob string `json:"newjob"`
	// Display sort order of the row's category.
	CategoryOrder string `json:"capord"`
	// Display sort order of the row's location.
	LocationOrder string `json:"locord"`
}

// GetJobCode returns the value of JobCode.
func (s *Job) GetJobCode() string {
	return s.JobCode
}

// GetSerial returns the value of Serial.
func (s *Job) GetSerial() string {
	return s.Serial
}

// GetCategoryID returns the value of CategoryID.
func (s *Job) GetCategoryID() string {
	return s.CategoryID
}

// GetCategoryName returns the value of CategoryName.
func (s *Job) GetCategoryName() string {
	return s.CategoryName
}

// GetCataID returns the value of CataID.
func (s *Job) GetCataID() string {
	return s.CataID
}

// GetTitle returns the value of Title.
func (s *Job) GetTitle() string {
	return s.Title
}

// GetLocationID returns the value of LocationID.
func (s *Job) GetLocationID() string {
	return s.LocationID
}

// GetLocationName returns the value of LocationName.
func (s *Job) GetLocationName() string {
	return s.LocationName
}

// GetPostedExternal returns the value of PostedExternal.
func (s *Job) GetPostedExternal() string {
	return s.PostedExternal
}

// GetPostedInternal returns the value of PostedInternal.
func (s *Job) GetPostedInternal() string {
	return s.PostedInternal
}

// GetCancelled returns the value of Cancelled.
func (s *Job) GetCancelled() string {
	return s.Cancelled
}

// GetIsCont returns the value of IsCont.
func (s *Job) GetIsCont() string {
	return s.IsCont
}

// GetRequirements returns the value of Requirements.
func (s *Job) GetRequirements() NilString {
	return s.Requirements
}

// GetDescription returns the value of Description.
func (s *Job) GetDescription() string {
	return s.Description
}

// GetKeywords returns the value of Keywords.
func (s *Job) GetKeywords() string {
	return s.Keywords
}

// GetHotOrder returns the value of HotOrder.
func (s *Job) GetHotOrder() string {
	return s.HotOrder
}

// GetSalary returns the value of Salary.
func (s *Job) GetSalary() string {
	return s.Salary
}

// GetNewJob returns the value of NewJob.
func (s *Job) GetNewJob() string {
	return s.NewJob
}

// GetCategoryOrder returns the value of CategoryOrder.
func (s *Job) GetCategoryOrder() string {
	return s.CategoryOrder
}

// GetLocationOrder returns the value of LocationOrder.
func (s *Job) GetLocationOrder() string {
	return s.LocationOrder
}

// SetJobCode sets the value of JobCode.
func (s *Job) SetJobCode(val string) {
	s.JobCode = val
}

// SetSerial sets the value of Serial.
func (s *Job) SetSerial(val string) {
	s.Serial = val
}

// SetCategoryID sets the value of CategoryID.
func (s *Job) SetCategoryID(val string) {
	s.CategoryID = val
}

// SetCategoryName sets the value of CategoryName.
func (s *Job) SetCategoryName(val string) {
	s.CategoryName = val
}

// SetCataID sets the value of CataID.
func (s *Job) SetCataID(val string) {
	s.CataID = val
}

// SetTitle sets the value of Title.
func (s *Job) SetTitle(val string) {
	s.Title = val
}

// SetLocationID sets the value of LocationID.
func (s *Job) SetLocationID(val string) {
	s.LocationID = val
}

// SetLocationName sets the value of LocationName.
func (s *Job) SetLocationName(val string) {
	s.LocationName = val
}

// SetPostedExternal sets the value of PostedExternal.
func (s *Job) SetPostedExternal(val string) {
	s.PostedExternal = val
}

// SetPostedInternal sets the value of PostedInternal.
func (s *Job) SetPostedInternal(val string) {
	s.PostedInternal = val
}

// SetCancelled sets the value of Cancelled.
func (s *Job) SetCancelled(val string) {
	s.Cancelled = val
}

// SetIsCont sets the value of IsCont.
func (s *Job) SetIsCont(val string) {
	s.IsCont = val
}

// SetRequirements sets the value of Requirements.
func (s *Job) SetRequirements(val NilString) {
	s.Requirements = val
}

// SetDescription sets the value of Description.
func (s *Job) SetDescription(val string) {
	s.Description = val
}

// SetKeywords sets the value of Keywords.
func (s *Job) SetKeywords(val string) {
	s.Keywords = val
}

// SetHotOrder sets the value of HotOrder.
func (s *Job) SetHotOrder(val string) {
	s.HotOrder = val
}

// SetSalary sets the value of Salary.
func (s *Job) SetSalary(val string) {
	s.Salary = val
}

// SetNewJob sets the value of NewJob.
func (s *Job) SetNewJob(val string) {
	s.NewJob = val
}

// SetCategoryOrder sets the value of CategoryOrder.
func (s *Job) SetCategoryOrder(val string) {
	s.CategoryOrder = val
}

// SetLocationOrder sets the value of LocationOrder.
func (s *Job) SetLocationOrder(val string) {
	s.LocationOrder = val
}

// Response envelope. `jobResult` is the only key the live endpoint returns; the `category`/`location`
// keys the page script probes for have never been observed.
// Ref: #/components/schemas/JobList
type JobList struct {
	JobResult []Job `json:"jobResult"`
}

// GetJobResult returns the value of JobResult.
func (s *JobList) GetJobResult() []Job {
	return s.JobResult
}

// SetJobResult sets the value of JobResult.
func (s *JobList) SetJobResult(val []Job) {
	s.JobResult = val
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
