// Code generated by ogen, DO NOT EDIT.

package remotive

// OperationName is the ogen operation name
type OperationName = string

const (
	ListCategoriesOperation OperationName = "ListCategories"
	ListJobsOperation       OperationName = "ListJobs"
)
