// Code generated by ogen, DO NOT EDIT.

package remotive

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ListCategories implements listCategories operation.
	//
	// Returns the category list wrapped in the same envelope as the jobs endpoint — categories arrive
	// under the `jobs` key and `job-count` holds the category count.
	//
	// GET /remote-jobs/categories
	ListCategories(ctx context.Context) (*CategoryList, error)
	// ListJobs implements listJobs operation.
	//
	// Returns every job the free API currently exposes, with full HTML descriptions inline. The documented
	// query parameters are no-ops (see the API description) — search, category, company, and limit
	// narrowing all happen client-side.
	//
	// GET /remote-jobs
	ListJobs(ctx context.Context) (*JobList, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
