// Code generated by ogen, DO NOT EDIT.

package googlejobs

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// SearchJobsInitial implements searchJobsInitial operation.
//
// Returns the first Google Jobs result page and, when more results are available, a forward cursor in
// a `data-async-fc` HTML attribute.
//
// The caller must construct `q` before making this request. The higher-level JobSpy query synthesis
// documented above is client behavior and is not a set of independent server-side filters.
//
// GET /search
func (UnimplementedHandler) SearchJobsInitial(ctx context.Context, params SearchJobsInitialParams) (r SearchJobsInitialRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchJobsNextPage implements searchJobsNextPage operation.
//
// Exchanges the forward cursor from the preceding response for another job batch and an optional next
// cursor. JobSpy repeats this operation while a cursor exists and more unique result URLs are needed.
//
// The response is a private text envelope rather than a normal JSON document. JobSpy locates the outer
// `[[[ ... ]]]` segment, JSON-decodes it, then JSON-decodes nested strings and recursively searches
// each value for the numeric key `520084652`.
//
// GET /async/callback:550
func (UnimplementedHandler) SearchJobsNextPage(ctx context.Context, params SearchJobsNextPageParams) (r SearchJobsNextPageRes, _ error) {
	return r, ht.ErrNotImplemented
}
