// Code generated by ogen, DO NOT EDIT.

package googlejobs

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// SearchJobsInitialParams is parameters of searchJobsInitial operation.
type SearchJobsInitialParams struct {
	// Complete Google Jobs query. Pass either JobSpy's synthesized phrase or `google_search_term`
	// unchanged when that override is supplied.
	Q string
	// Selects Google's Jobs result mode. JobSpy always sends the literal `8`. Other values select
	// different Google search verticals and are outside this specification.
	Udm SearchJobsInitialUdm
	// Preferred response language. JobSpy sends `en-US,en;q=0.9`; parser-visible labels and relative dates
	// can change when another locale is used.
	AcceptLanguage OptString `json:",omitempty,omitzero"`
	// Browser user agent. JobSpy sends a desktop Chromium identity together with additional browser
	// client-hint and fetch-metadata headers. Those volatile headers are intentionally not enumerated as a
	// stable API contract.
	UserAgent OptString `json:",omitempty,omitzero"`
}

func unpackSearchJobsInitialParams(packed middleware.Parameters) (params SearchJobsInitialParams) {
	{
		key := middleware.ParameterKey{
			Name: "q",
			In:   "query",
		}
		params.Q = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "udm",
			In:   "query",
		}
		params.Udm = packed[key].(SearchJobsInitialUdm)
	}
	{
		key := middleware.ParameterKey{
			Name: "Accept-Language",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.AcceptLanguage = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "User-Agent",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.UserAgent = v.(OptString)
		}
	}
	return params
}

func decodeSearchJobsInitialParams(args [0]string, argsEscaped bool, r *http.Request) (params SearchJobsInitialParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	h := uri.NewHeaderDecoder(r.Header)
	// Decode query: q.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "q",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Q = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Q)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "q",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: udm.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "udm",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Udm = SearchJobsInitialUdm(c)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Udm.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "udm",
			In:   "query",
			Err:  err,
		}
	}
	// Decode header: Accept-Language.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Accept-Language",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAcceptLanguageVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAcceptLanguageVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.AcceptLanguage.SetTo(paramsDotAcceptLanguageVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Accept-Language",
			In:   "header",
			Err:  err,
		}
	}
	// Decode header: User-Agent.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "User-Agent",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUserAgentVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotUserAgentVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.UserAgent.SetTo(paramsDotUserAgentVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "User-Agent",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// SearchJobsNextPageParams is parameters of searchJobsNextPage operation.
type SearchJobsNextPageParams struct {
	// Opaque forward cursor copied exactly from the preceding response's `data-async-fc` attribute. Do not
	// decode or modify it.
	Fc string
	// Cursor protocol version. JobSpy always sends the literal `3`.
	Fcv SearchJobsNextPageFcv
	// Opaque Google frontend bootstrap descriptor. The JobSpy upstream keeps a literal snapshot containing
	// `_basejs`, `_basecss`, `_basecomb`, and formatting identifiers. Copy the current upstream value
	// exactly. It is versioned frontend state, not a durable API token; when it expires or Google deploys
	// new assets, the client implementation may need updating.
	Async string
	// Preferred response language. JobSpy sends `en-US,en;q=0.9`; parser-visible labels and relative dates
	// can change when another locale is used.
	AcceptLanguage OptString `json:",omitempty,omitzero"`
	// Browser user agent. JobSpy sends a desktop Chromium identity together with additional browser
	// client-hint and fetch-metadata headers. Those volatile headers are intentionally not enumerated as a
	// stable API contract.
	UserAgent OptString `json:",omitempty,omitzero"`
}

func unpackSearchJobsNextPageParams(packed middleware.Parameters) (params SearchJobsNextPageParams) {
	{
		key := middleware.ParameterKey{
			Name: "fc",
			In:   "query",
		}
		params.Fc = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "fcv",
			In:   "query",
		}
		params.Fcv = packed[key].(SearchJobsNextPageFcv)
	}
	{
		key := middleware.ParameterKey{
			Name: "async",
			In:   "query",
		}
		params.Async = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "Accept-Language",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.AcceptLanguage = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "User-Agent",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.UserAgent = v.(OptString)
		}
	}
	return params
}

func decodeSearchJobsNextPageParams(args [0]string, argsEscaped bool, r *http.Request) (params SearchJobsNextPageParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	h := uri.NewHeaderDecoder(r.Header)
	// Decode query: fc.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "fc",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Fc = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Fc)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fc",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: fcv.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "fcv",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Fcv = SearchJobsNextPageFcv(c)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Fcv.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fcv",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: async.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "async",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Async = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Async)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "async",
			In:   "query",
			Err:  err,
		}
	}
	// Decode header: Accept-Language.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Accept-Language",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAcceptLanguageVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAcceptLanguageVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.AcceptLanguage.SetTo(paramsDotAcceptLanguageVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Accept-Language",
			In:   "header",
			Err:  err,
		}
	}
	// Decode header: User-Agent.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "User-Agent",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUserAgentVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotUserAgentVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.UserAgent.SetTo(paramsDotUserAgentVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "User-Agent",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
