// Code generated by ogen, DO NOT EDIT.

package googlejobs

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// SearchJobsInitial implements searchJobsInitial operation.
	//
	// Returns the first Google Jobs result page and, when more results are available, a forward cursor in
	// a `data-async-fc` HTML attribute.
	//
	// The caller must construct `q` before making this request. The higher-level JobSpy query synthesis
	// documented above is client behavior and is not a set of independent server-side filters.
	//
	// GET /search
	SearchJobsInitial(ctx context.Context, params SearchJobsInitialParams) (SearchJobsInitialRes, error)
	// SearchJobsNextPage implements searchJobsNextPage operation.
	//
	// Exchanges the forward cursor from the preceding response for another job batch and an optional next
	// cursor. JobSpy repeats this operation while a cursor exists and more unique result URLs are needed.
	//
	// The response is a private text envelope rather than a normal JSON document. JobSpy locates the outer
	// `[[[ ... ]]]` segment, JSON-decodes it, then JSON-decodes nested strings and recursively searches
	// each value for the numeric key `520084652`.
	//
	// GET /async/callback:550
	SearchJobsNextPage(ctx context.Context, params SearchJobsNextPageParams) (SearchJobsNextPageRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
