// Code generated by ogen, DO NOT EDIT.

package googlejobs

// OperationName is the ogen operation name
type OperationName = string

const (
	SearchJobsInitialOperation  OperationName = "SearchJobsInitial"
	SearchJobsNextPageOperation OperationName = "SearchJobsNextPage"
)
