// Code generated by ogen, DO NOT EDIT.

package googlejobs

import (
	"github.com/go-faster/errors"
)

func (s SearchJobsInitialUdm) Validate() error {
	switch s {
	case "8":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s SearchJobsNextPageFcv) Validate() error {
	switch s {
	case "3":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
