// Code generated by ogen, DO NOT EDIT.

package googlejobs

import (
	"io"

	"github.com/go-faster/errors"
)

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Server-rendered Google Search HTML with embedded job arrays.
type SearchJobsInitialOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s SearchJobsInitialOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*SearchJobsInitialOK) searchJobsInitialRes() {}

type SearchJobsInitialUdm string

const (
	SearchJobsInitialUdm8 SearchJobsInitialUdm = "8"
)

// AllValues returns all SearchJobsInitialUdm values.
func (SearchJobsInitialUdm) AllValues() []SearchJobsInitialUdm {
	return []SearchJobsInitialUdm{
		SearchJobsInitialUdm8,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SearchJobsInitialUdm) MarshalText() ([]byte, error) {
	switch s {
	case SearchJobsInitialUdm8:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SearchJobsInitialUdm) UnmarshalText(data []byte) error {
	switch SearchJobsInitialUdm(data) {
	case SearchJobsInitialUdm8:
		*s = SearchJobsInitialUdm8
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type SearchJobsNextPageFcv string

const (
	SearchJobsNextPageFcv3 SearchJobsNextPageFcv = "3"
)

// AllValues returns all SearchJobsNextPageFcv values.
func (SearchJobsNextPageFcv) AllValues() []SearchJobsNextPageFcv {
	return []SearchJobsNextPageFcv{
		SearchJobsNextPageFcv3,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SearchJobsNextPageFcv) MarshalText() ([]byte, error) {
	switch s {
	case SearchJobsNextPageFcv3:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SearchJobsNextPageFcv) UnmarshalText(data []byte) error {
	switch SearchJobsNextPageFcv(data) {
	case SearchJobsNextPageFcv3:
		*s = SearchJobsNextPageFcv3
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// HTML or challenge response returned instead of the expected envelope.
type SearchJobsNextPageOKTextHTML struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s SearchJobsNextPageOKTextHTML) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*SearchJobsNextPageOKTextHTML) searchJobsNextPageRes() {}

// Private Google async envelope containing nested JSON strings.
type SearchJobsNextPageOKTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s SearchJobsNextPageOKTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*SearchJobsNextPageOKTextPlain) searchJobsNextPageRes() {}

type UnexpectedResponseTextHTML struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s UnexpectedResponseTextHTML) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// UnexpectedResponseTextHTMLStatusCode wraps UnexpectedResponseTextHTML with StatusCode.
type UnexpectedResponseTextHTMLStatusCode struct {
	StatusCode int
	Response   UnexpectedResponseTextHTML
}

// GetStatusCode returns the value of StatusCode.
func (s *UnexpectedResponseTextHTMLStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *UnexpectedResponseTextHTMLStatusCode) GetResponse() UnexpectedResponseTextHTML {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *UnexpectedResponseTextHTMLStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *UnexpectedResponseTextHTMLStatusCode) SetResponse(val UnexpectedResponseTextHTML) {
	s.Response = val
}

func (*UnexpectedResponseTextHTMLStatusCode) searchJobsInitialRes()  {}
func (*UnexpectedResponseTextHTMLStatusCode) searchJobsNextPageRes() {}

type UnexpectedResponseTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s UnexpectedResponseTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// UnexpectedResponseTextPlainStatusCode wraps UnexpectedResponseTextPlain with StatusCode.
type UnexpectedResponseTextPlainStatusCode struct {
	StatusCode int
	Response   UnexpectedResponseTextPlain
}

// GetStatusCode returns the value of StatusCode.
func (s *UnexpectedResponseTextPlainStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *UnexpectedResponseTextPlainStatusCode) GetResponse() UnexpectedResponseTextPlain {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *UnexpectedResponseTextPlainStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *UnexpectedResponseTextPlainStatusCode) SetResponse(val UnexpectedResponseTextPlain) {
	s.Response = val
}

func (*UnexpectedResponseTextPlainStatusCode) searchJobsInitialRes()  {}
func (*UnexpectedResponseTextPlainStatusCode) searchJobsNextPageRes() {}
