// Code generated by ogen, DO NOT EDIT.

package eightfold

// OperationName is the ogen operation name
type OperationName = string

const (
	PositionDetailsOperation   OperationName = "PositionDetails"
	PositionDetailsV2Operation OperationName = "PositionDetailsV2"
	SearchOperation            OperationName = "Search"
	SearchV2Operation          OperationName = "SearchV2"
)
