// Code generated by ogen, DO NOT EDIT.

package himalayas

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/Job
type Job struct {
	// Job title.
	Title string `json:"title"`
	// Short plain-text summary of the job.
	Excerpt string `json:"excerpt"`
	// Name of the hiring company.
	CompanyName string `json:"companyName"`
	// Canonical company slug for the search endpoint's company filter and himalayas.app/companies/ pages.
	CompanySlug string `json:"companySlug"`
	// URL of the company logo image.
	CompanyLogo string `json:"companyLogo"`
	// Type of employment. 'Contractor' includes freelance and contract roles.
	EmploymentType JobEmploymentType `json:"employmentType"`
	// Minimum salary in the pay period specified by salaryPeriod, in the currency field. Null if not
	// disclosed.
	MinSalary OptNilFloat64 `json:"minSalary"`
	// Maximum salary in the pay period specified by salaryPeriod, in the currency field. Null if not
	// disclosed.
	MaxSalary OptNilFloat64 `json:"maxSalary"`
	// Pay period for minSalary and maxSalary. Legacy listings without an explicit period report annual.
	SalaryPeriod JobSalaryPeriod `json:"salaryPeriod"`
	// Required seniority levels. A job may accept multiple levels (e.g., both Mid-level and Senior).
	Seniority []JobSeniorityItem `json:"seniority"`
	// ISO 4217 currency code for the salary. Null whenever no salary is disclosed (the official document's
	// required enum is wrong on both counts).
	Currency NilString `json:"currency"`
	// Country names (plain strings, not the official document's Location objects) where candidates must be
	// located. An empty array means the job is open worldwide.
	LocationRestrictions []string `json:"locationRestrictions"`
	// Numeric UTC offsets the candidate must overlap with — integers or fractional offsets like -3.5 or
	// 5.75 (not the official document's "UTC-5" strings). An empty array means no timezone requirement.
	TimezoneRestrictions []float64 `json:"timezoneRestrictions"`
	// Job categories and skills, such as 'React' or 'Product Management'. A dynamic set — match with
	// substring or fuzzy matching.
	Categories []string `json:"categories"`
	// Broad job function categories such as 'Engineering' or 'Marketing'. May be empty.
	ParentCategories []string `json:"parentCategories"`
	// Full job description as sanitized HTML. The feed carries the complete posting body; there is no
	// separate detail endpoint.
	Description string `json:"description"`
	// Unix timestamp in seconds (not milliseconds, despite the official document) when the job was
	// published.
	PubDate int64 `json:"pubDate"`
	// Unix timestamp in seconds (not milliseconds, despite the official document) when the job expires.
	ExpiryDate int64 `json:"expiryDate"`
	// The job's posting page on himalayas.app. Equal to guid in every sampled job.
	ApplicationLink string `json:"applicationLink"`
	// Unique identifier for the job listing — the job's public himalayas.app posting URL.
	GUID string `json:"guid"`
}

// GetTitle returns the value of Title.
func (s *Job) GetTitle() string {
	return s.Title
}

// GetExcerpt returns the value of Excerpt.
func (s *Job) GetExcerpt() string {
	return s.Excerpt
}

// GetCompanyName returns the value of CompanyName.
func (s *Job) GetCompanyName() string {
	return s.CompanyName
}

// GetCompanySlug returns the value of CompanySlug.
func (s *Job) GetCompanySlug() string {
	return s.CompanySlug
}

// GetCompanyLogo returns the value of CompanyLogo.
func (s *Job) GetCompanyLogo() string {
	return s.CompanyLogo
}

// GetEmploymentType returns the value of EmploymentType.
func (s *Job) GetEmploymentType() JobEmploymentType {
	return s.EmploymentType
}

// GetMinSalary returns the value of MinSalary.
func (s *Job) GetMinSalary() OptNilFloat64 {
	return s.MinSalary
}

// GetMaxSalary returns the value of MaxSalary.
func (s *Job) GetMaxSalary() OptNilFloat64 {
	return s.MaxSalary
}

// GetSalaryPeriod returns the value of SalaryPeriod.
func (s *Job) GetSalaryPeriod() JobSalaryPeriod {
	return s.SalaryPeriod
}

// GetSeniority returns the value of Seniority.
func (s *Job) GetSeniority() []JobSeniorityItem {
	return s.Seniority
}

// GetCurrency returns the value of Currency.
func (s *Job) GetCurrency() NilString {
	return s.Currency
}

// GetLocationRestrictions returns the value of LocationRestrictions.
func (s *Job) GetLocationRestrictions() []string {
	return s.LocationRestrictions
}

// GetTimezoneRestrictions returns the value of TimezoneRestrictions.
func (s *Job) GetTimezoneRestrictions() []float64 {
	return s.TimezoneRestrictions
}

// GetCategories returns the value of Categories.
func (s *Job) GetCategories() []string {
	return s.Categories
}

// GetParentCategories returns the value of ParentCategories.
func (s *Job) GetParentCategories() []string {
	return s.ParentCategories
}

// GetDescription returns the value of Description.
func (s *Job) GetDescription() string {
	return s.Description
}

// GetPubDate returns the value of PubDate.
func (s *Job) GetPubDate() int64 {
	return s.PubDate
}

// GetExpiryDate returns the value of ExpiryDate.
func (s *Job) GetExpiryDate() int64 {
	return s.ExpiryDate
}

// GetApplicationLink returns the value of ApplicationLink.
func (s *Job) GetApplicationLink() string {
	return s.ApplicationLink
}

// GetGUID returns the value of GUID.
func (s *Job) GetGUID() string {
	return s.GUID
}

// SetTitle sets the value of Title.
func (s *Job) SetTitle(val string) {
	s.Title = val
}

// SetExcerpt sets the value of Excerpt.
func (s *Job) SetExcerpt(val string) {
	s.Excerpt = val
}

// SetCompanyName sets the value of CompanyName.
func (s *Job) SetCompanyName(val string) {
	s.CompanyName = val
}

// SetCompanySlug sets the value of CompanySlug.
func (s *Job) SetCompanySlug(val string) {
	s.CompanySlug = val
}

// SetCompanyLogo sets the value of CompanyLogo.
func (s *Job) SetCompanyLogo(val string) {
	s.CompanyLogo = val
}

// SetEmploymentType sets the value of EmploymentType.
func (s *Job) SetEmploymentType(val JobEmploymentType) {
	s.EmploymentType = val
}

// SetMinSalary sets the value of MinSalary.
func (s *Job) SetMinSalary(val OptNilFloat64) {
	s.MinSalary = val
}

// SetMaxSalary sets the value of MaxSalary.
func (s *Job) SetMaxSalary(val OptNilFloat64) {
	s.MaxSalary = val
}

// SetSalaryPeriod sets the value of SalaryPeriod.
func (s *Job) SetSalaryPeriod(val JobSalaryPeriod) {
	s.SalaryPeriod = val
}

// SetSeniority sets the value of Seniority.
func (s *Job) SetSeniority(val []JobSeniorityItem) {
	s.Seniority = val
}

// SetCurrency sets the value of Currency.
func (s *Job) SetCurrency(val NilString) {
	s.Currency = val
}

// SetLocationRestrictions sets the value of LocationRestrictions.
func (s *Job) SetLocationRestrictions(val []string) {
	s.LocationRestrictions = val
}

// SetTimezoneRestrictions sets the value of TimezoneRestrictions.
func (s *Job) SetTimezoneRestrictions(val []float64) {
	s.TimezoneRestrictions = val
}

// SetCategories sets the value of Categories.
func (s *Job) SetCategories(val []string) {
	s.Categories = val
}

// SetParentCategories sets the value of ParentCategories.
func (s *Job) SetParentCategories(val []string) {
	s.ParentCategories = val
}

// SetDescription sets the value of Description.
func (s *Job) SetDescription(val string) {
	s.Description = val
}

// SetPubDate sets the value of PubDate.
func (s *Job) SetPubDate(val int64) {
	s.PubDate = val
}

// SetExpiryDate sets the value of ExpiryDate.
func (s *Job) SetExpiryDate(val int64) {
	s.ExpiryDate = val
}

// SetApplicationLink sets the value of ApplicationLink.
func (s *Job) SetApplicationLink(val string) {
	s.ApplicationLink = val
}

// SetGUID sets the value of GUID.
func (s *Job) SetGUID(val string) {
	s.GUID = val
}

// Type of employment. 'Contractor' includes freelance and contract roles.
type JobEmploymentType string

const (
	JobEmploymentTypeFullTime   JobEmploymentType = "Full Time"
	JobEmploymentTypePartTime   JobEmploymentType = "Part Time"
	JobEmploymentTypeContractor JobEmploymentType = "Contractor"
	JobEmploymentTypeTemporary  JobEmploymentType = "Temporary"
	JobEmploymentTypeIntern     JobEmploymentType = "Intern"
	JobEmploymentTypeVolunteer  JobEmploymentType = "Volunteer"
	JobEmploymentTypeOther      JobEmploymentType = "Other"
)

// AllValues returns all JobEmploymentType values.
func (JobEmploymentType) AllValues() []JobEmploymentType {
	return []JobEmploymentType{
		JobEmploymentTypeFullTime,
		JobEmploymentTypePartTime,
		JobEmploymentTypeContractor,
		JobEmploymentTypeTemporary,
		JobEmploymentTypeIntern,
		JobEmploymentTypeVolunteer,
		JobEmploymentTypeOther,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s JobEmploymentType) MarshalText() ([]byte, error) {
	switch s {
	case JobEmploymentTypeFullTime:
		return []byte(s), nil
	case JobEmploymentTypePartTime:
		return []byte(s), nil
	case JobEmploymentTypeContractor:
		return []byte(s), nil
	case JobEmploymentTypeTemporary:
		return []byte(s), nil
	case JobEmploymentTypeIntern:
		return []byte(s), nil
	case JobEmploymentTypeVolunteer:
		return []byte(s), nil
	case JobEmploymentTypeOther:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *JobEmploymentType) UnmarshalText(data []byte) error {
	switch JobEmploymentType(data) {
	case JobEmploymentTypeFullTime:
		*s = JobEmploymentTypeFullTime
		return nil
	case JobEmploymentTypePartTime:
		*s = JobEmploymentTypePartTime
		return nil
	case JobEmploymentTypeContractor:
		*s = JobEmploymentTypeContractor
		return nil
	case JobEmploymentTypeTemporary:
		*s = JobEmploymentTypeTemporary
		return nil
	case JobEmploymentTypeIntern:
		*s = JobEmploymentTypeIntern
		return nil
	case JobEmploymentTypeVolunteer:
		*s = JobEmploymentTypeVolunteer
		return nil
	case JobEmploymentTypeOther:
		*s = JobEmploymentTypeOther
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Pay period for minSalary and maxSalary. Legacy listings without an explicit period report annual.
type JobSalaryPeriod string

const (
	JobSalaryPeriodHourly      JobSalaryPeriod = "hourly"
	JobSalaryPeriodWeekly      JobSalaryPeriod = "weekly"
	JobSalaryPeriodFortnightly JobSalaryPeriod = "fortnightly"
	JobSalaryPeriodMonthly     JobSalaryPeriod = "monthly"
	JobSalaryPeriodAnnual      JobSalaryPeriod = "annual"
)

// AllValues returns all JobSalaryPeriod values.
func (JobSalaryPeriod) AllValues() []JobSalaryPeriod {
	return []JobSalaryPeriod{
		JobSalaryPeriodHourly,
		JobSalaryPeriodWeekly,
		JobSalaryPeriodFortnightly,
		JobSalaryPeriodMonthly,
		JobSalaryPeriodAnnual,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s JobSalaryPeriod) MarshalText() ([]byte, error) {
	switch s {
	case JobSalaryPeriodHourly:
		return []byte(s), nil
	case JobSalaryPeriodWeekly:
		return []byte(s), nil
	case JobSalaryPeriodFortnightly:
		return []byte(s), nil
	case JobSalaryPeriodMonthly:
		return []byte(s), nil
	case JobSalaryPeriodAnnual:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *JobSalaryPeriod) UnmarshalText(data []byte) error {
	switch JobSalaryPeriod(data) {
	case JobSalaryPeriodHourly:
		*s = JobSalaryPeriodHourly
		return nil
	case JobSalaryPeriodWeekly:
		*s = JobSalaryPeriodWeekly
		return nil
	case JobSalaryPeriodFortnightly:
		*s = JobSalaryPeriodFortnightly
		return nil
	case JobSalaryPeriodMonthly:
		*s = JobSalaryPeriodMonthly
		return nil
	case JobSalaryPeriodAnnual:
		*s = JobSalaryPeriodAnnual
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type JobSeniorityItem string

const (
	JobSeniorityItemEntryLevel JobSeniorityItem = "Entry-level"
	JobSeniorityItemMidLevel   JobSeniorityItem = "Mid-level"
	JobSeniorityItemSenior     JobSeniorityItem = "Senior"
	JobSeniorityItemManager    JobSeniorityItem = "Manager"
	JobSeniorityItemDirector   JobSeniorityItem = "Director"
	JobSeniorityItemExecutive  JobSeniorityItem = "Executive"
)

// AllValues returns all JobSeniorityItem values.
func (JobSeniorityItem) AllValues() []JobSeniorityItem {
	return []JobSeniorityItem{
		JobSeniorityItemEntryLevel,
		JobSeniorityItemMidLevel,
		JobSeniorityItemSenior,
		JobSeniorityItemManager,
		JobSeniorityItemDirector,
		JobSeniorityItemExecutive,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s JobSeniorityItem) MarshalText() ([]byte, error) {
	switch s {
	case JobSeniorityItemEntryLevel:
		return []byte(s), nil
	case JobSeniorityItemMidLevel:
		return []byte(s), nil
	case JobSeniorityItemSenior:
		return []byte(s), nil
	case JobSeniorityItemManager:
		return []byte(s), nil
	case JobSeniorityItemDirector:
		return []byte(s), nil
	case JobSeniorityItemExecutive:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *JobSeniorityItem) UnmarshalText(data []byte) error {
	switch JobSeniorityItem(data) {
	case JobSeniorityItemEntryLevel:
		*s = JobSeniorityItemEntryLevel
		return nil
	case JobSeniorityItemMidLevel:
		*s = JobSeniorityItemMidLevel
		return nil
	case JobSeniorityItemSenior:
		*s = JobSeniorityItemSenior
		return nil
	case JobSeniorityItemManager:
		*s = JobSeniorityItemManager
		return nil
	case JobSeniorityItemDirector:
		*s = JobSeniorityItemDirector
		return nil
	case JobSeniorityItemExecutive:
		*s = JobSeniorityItemExecutive
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/JobsResponse
type JobsResponse struct {
	// Release notes or changelog for the Himalayas API.
	Comments OptString `json:"comments"`
	// Unix timestamp in seconds (not milliseconds, despite the official document) when the data was last
	// updated.
	UpdatedAt int64 `json:"updatedAt"`
	// The offset used in this request. The search endpoint reports the offset equivalent of its page
	// parameter ((page-1)*20).
	Offset int `json:"offset"`
	// The limit used in this request.
	Limit int `json:"limit"`
	// Total number of matching jobs across all pages. A page may still hold fewer than limit jobs before
	// the last page.
	TotalCount int   `json:"totalCount"`
	Jobs       []Job `json:"jobs"`
}

// GetComments returns the value of Comments.
func (s *JobsResponse) GetComments() OptString {
	return s.Comments
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *JobsResponse) GetUpdatedAt() int64 {
	return s.UpdatedAt
}

// GetOffset returns the value of Offset.
func (s *JobsResponse) GetOffset() int {
	return s.Offset
}

// GetLimit returns the value of Limit.
func (s *JobsResponse) GetLimit() int {
	return s.Limit
}

// GetTotalCount returns the value of TotalCount.
func (s *JobsResponse) GetTotalCount() int {
	return s.TotalCount
}

// GetJobs returns the value of Jobs.
func (s *JobsResponse) GetJobs() []Job {
	return s.Jobs
}

// SetComments sets the value of Comments.
func (s *JobsResponse) SetComments(val OptString) {
	s.Comments = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *JobsResponse) SetUpdatedAt(val int64) {
	s.UpdatedAt = val
}

// SetOffset sets the value of Offset.
func (s *JobsResponse) SetOffset(val int) {
	s.Offset = val
}

// SetLimit sets the value of Limit.
func (s *JobsResponse) SetLimit(val int) {
	s.Limit = val
}

// SetTotalCount sets the value of TotalCount.
func (s *JobsResponse) SetTotalCount(val int) {
	s.TotalCount = val
}

// SetJobs sets the value of Jobs.
func (s *JobsResponse) SetJobs(val []Job) {
	s.Jobs = val
}

func (*JobsResponse) searchJobsRes() {}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilFloat64 returns new OptNilFloat64 with value set to v.
func NewOptNilFloat64(v float64) OptNilFloat64 {
	return OptNilFloat64{
		Value: v,
		Set:   true,
	}
}

// OptNilFloat64 is optional nullable float64.
type OptNilFloat64 struct {
	Value float64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilFloat64 was set.
func (o OptNilFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilFloat64) SetTo(v float64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilFloat64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilFloat64) SetToNull() {
	o.Set = true
	o.Null = true
	var v float64
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilFloat64) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilFloat64) Get() (v float64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSearchJobsSort returns new OptSearchJobsSort with value set to v.
func NewOptSearchJobsSort(v SearchJobsSort) OptSearchJobsSort {
	return OptSearchJobsSort{
		Value: v,
		Set:   true,
	}
}

// OptSearchJobsSort is optional SearchJobsSort.
type OptSearchJobsSort struct {
	Value SearchJobsSort
	Set   bool
}

// IsSet returns true if OptSearchJobsSort was set.
func (o OptSearchJobsSort) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSearchJobsSort) Reset() {
	var v SearchJobsSort
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSearchJobsSort) SetTo(v SearchJobsSort) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSearchJobsSort) Get() (v SearchJobsSort, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSearchJobsSort) Or(d SearchJobsSort) SearchJobsSort {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Observed 400 body of the search endpoint, e.g. {"ok": false, "errors": "Invalid country"}. Differs
// from the officially documented {"error": "..."} shape.
// Ref: #/components/schemas/SearchError
type SearchError struct {
	Ok     bool   `json:"ok"`
	Errors string `json:"errors"`
}

// GetOk returns the value of Ok.
func (s *SearchError) GetOk() bool {
	return s.Ok
}

// GetErrors returns the value of Errors.
func (s *SearchError) GetErrors() string {
	return s.Errors
}

// SetOk sets the value of Ok.
func (s *SearchError) SetOk(val bool) {
	s.Ok = val
}

// SetErrors sets the value of Errors.
func (s *SearchError) SetErrors(val string) {
	s.Errors = val
}

func (*SearchError) searchJobsRes() {}

type SearchJobsSort string

const (
	SearchJobsSortRelevant   SearchJobsSort = "relevant"
	SearchJobsSortRecent     SearchJobsSort = "recent"
	SearchJobsSortSalaryAsc  SearchJobsSort = "salaryAsc"
	SearchJobsSortSalaryDesc SearchJobsSort = "salaryDesc"
	SearchJobsSortNameAToZ   SearchJobsSort = "nameAToZ"
	SearchJobsSortNameZToA   SearchJobsSort = "nameZToA"
	SearchJobsSortJobs       SearchJobsSort = "jobs"
)

// AllValues returns all SearchJobsSort values.
func (SearchJobsSort) AllValues() []SearchJobsSort {
	return []SearchJobsSort{
		SearchJobsSortRelevant,
		SearchJobsSortRecent,
		SearchJobsSortSalaryAsc,
		SearchJobsSortSalaryDesc,
		SearchJobsSortNameAToZ,
		SearchJobsSortNameZToA,
		SearchJobsSortJobs,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SearchJobsSort) MarshalText() ([]byte, error) {
	switch s {
	case SearchJobsSortRelevant:
		return []byte(s), nil
	case SearchJobsSortRecent:
		return []byte(s), nil
	case SearchJobsSortSalaryAsc:
		return []byte(s), nil
	case SearchJobsSortSalaryDesc:
		return []byte(s), nil
	case SearchJobsSortNameAToZ:
		return []byte(s), nil
	case SearchJobsSortNameZToA:
		return []byte(s), nil
	case SearchJobsSortJobs:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SearchJobsSort) UnmarshalText(data []byte) error {
	switch SearchJobsSort(data) {
	case SearchJobsSortRelevant:
		*s = SearchJobsSortRelevant
		return nil
	case SearchJobsSortRecent:
		*s = SearchJobsSortRecent
		return nil
	case SearchJobsSortSalaryAsc:
		*s = SearchJobsSortSalaryAsc
		return nil
	case SearchJobsSortSalaryDesc:
		*s = SearchJobsSortSalaryDesc
		return nil
	case SearchJobsSortNameAToZ:
		*s = SearchJobsSortNameAToZ
		return nil
	case SearchJobsSortNameZToA:
		*s = SearchJobsSortNameZToA
		return nil
	case SearchJobsSortJobs:
		*s = SearchJobsSortJobs
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
