// Code generated by ogen, DO NOT EDIT.

package himalayas

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *Job) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EmploymentType.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "employmentType",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.MinSalary.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "minSalary",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.MaxSalary.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "maxSalary",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.SalaryPeriod.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "salaryPeriod",
			Error: err,
		})
	}
	if err := func() error {
		if s.Seniority == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Seniority {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "seniority",
			Error: err,
		})
	}
	if err := func() error {
		if s.LocationRestrictions == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "locationRestrictions",
			Error: err,
		})
	}
	if err := func() error {
		if s.TimezoneRestrictions == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.TimezoneRestrictions {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(elem)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "timezoneRestrictions",
			Error: err,
		})
	}
	if err := func() error {
		if s.Categories == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "categories",
			Error: err,
		})
	}
	if err := func() error {
		if s.ParentCategories == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "parentCategories",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s JobEmploymentType) Validate() error {
	switch s {
	case "Full Time":
		return nil
	case "Part Time":
		return nil
	case "Contractor":
		return nil
	case "Temporary":
		return nil
	case "Intern":
		return nil
	case "Volunteer":
		return nil
	case "Other":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s JobSalaryPeriod) Validate() error {
	switch s {
	case "hourly":
		return nil
	case "weekly":
		return nil
	case "fortnightly":
		return nil
	case "monthly":
		return nil
	case "annual":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s JobSeniorityItem) Validate() error {
	switch s {
	case "Entry-level":
		return nil
	case "Mid-level":
		return nil
	case "Senior":
		return nil
	case "Manager":
		return nil
	case "Director":
		return nil
	case "Executive":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *JobsResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Jobs == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Jobs {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "jobs",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SearchJobsSort) Validate() error {
	switch s {
	case "relevant":
		return nil
	case "recent":
		return nil
	case "salaryAsc":
		return nil
	case "salaryDesc":
		return nil
	case "nameAToZ":
		return nil
	case "nameZToA":
		return nil
	case "jobs":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
