// Code generated by ogen, DO NOT EDIT.

package himalayas

// OperationName is the ogen operation name
type OperationName = string

const (
	BrowseJobsOperation OperationName = "BrowseJobs"
	SearchJobsOperation OperationName = "SearchJobs"
)
