// Code generated by ogen, DO NOT EDIT.

package himalayas

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// BrowseJobsParams is parameters of browseJobs operation.
type BrowseJobsParams struct {
	// Number of jobs per page. Maximum and default is 20.
	Limit OptInt `json:",omitempty,omitzero"`
	// Number of jobs to skip. Start at 0, then increment by limit. Use totalCount from the response to
	// know when to stop.
	Offset OptInt `json:",omitempty,omitzero"`
}

func unpackBrowseJobsParams(packed middleware.Parameters) (params BrowseJobsParams) {
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptInt)
		}
	}
	return params
}

func decodeBrowseJobsParams(args [0]string, argsEscaped bool, r *http.Request) (params BrowseJobsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: limit.
	{
		val := int(20)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           20,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: offset.
	{
		val := int(0)
		params.Offset.SetTo(val)
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Offset.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// SearchJobsParams is parameters of searchJobs operation.
type SearchJobsParams struct {
	// Free-text job search query. Fuzzy-relevance ranked — an unmatched keyword still returns fallback
	// results rather than an empty set.
	Q OptString `json:",omitempty,omitzero"`
	// Country filter. Supports ISO alpha-2, common country names, slugs, and common abbreviations.
	// Unrecognized values are a 400 "Invalid country".
	Country OptString `json:",omitempty,omitzero"`
	// Limit results to worldwide-friendly jobs.
	Worldwide OptBool `json:",omitempty,omitzero"`
	// Exclude worldwide matches when a country filter is present.
	ExcludeWorldwide OptBool `json:",omitempty,omitzero"`
	// Comma-separated seniority filters. Valid values are Entry-level, Mid-level, Senior, Manager,
	// Director, and Executive.
	Seniority OptString `json:",omitempty,omitzero"`
	// Comma-separated employment type filters. Valid values are Full Time, Part Time, Contractor,
	// Temporary, Intern, Volunteer, and Other.
	EmploymentType OptString `json:",omitempty,omitzero"`
	// Canonical Himalayas company slug (the slug in himalayas.app/companies/); supports comma-separated
	// values. An unrecognized slug is a 400 "Invalid company", not an empty result.
	Company OptString `json:",omitempty,omitzero"`
	// Timezone filter. Supports numeric UTC offsets and variants like `UTC-5` or `UTC+05:30`.
	Timezone OptString `json:",omitempty,omitzero"`
	// Sort order for results. 'relevant' ranks by best match to the query and filters (default). 'recent'
	// returns newest jobs first. 'salaryAsc'/'salaryDesc' sort by salary. 'nameAToZ'/ 'nameZToA' sort by
	// company name. 'jobs' sorts by companies with the most open roles first.
	Sort OptSearchJobsSort `json:",omitempty,omitzero"`
	// 1-based results page.
	Page OptInt `json:",omitempty,omitzero"`
}

func unpackSearchJobsParams(packed middleware.Parameters) (params SearchJobsParams) {
	{
		key := middleware.ParameterKey{
			Name: "q",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Q = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "country",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Country = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "worldwide",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Worldwide = v.(OptBool)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "exclude_worldwide",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ExcludeWorldwide = v.(OptBool)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "seniority",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Seniority = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "employment_type",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.EmploymentType = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "company",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Company = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "timezone",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Timezone = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "sort",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Sort = v.(OptSearchJobsSort)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "page",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Page = v.(OptInt)
		}
	}
	return params
}

func decodeSearchJobsParams(args [0]string, argsEscaped bool, r *http.Request) (params SearchJobsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: q.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "q",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotQVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotQVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Q.SetTo(paramsDotQVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "q",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: country.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "country",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCountryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCountryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Country.SetTo(paramsDotCountryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "country",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: worldwide.
	{
		val := bool(false)
		params.Worldwide.SetTo(val)
	}
	// Decode query: worldwide.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "worldwide",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotWorldwideVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotWorldwideVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Worldwide.SetTo(paramsDotWorldwideVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "worldwide",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: exclude_worldwide.
	{
		val := bool(false)
		params.ExcludeWorldwide.SetTo(val)
	}
	// Decode query: exclude_worldwide.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "exclude_worldwide",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExcludeWorldwideVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotExcludeWorldwideVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ExcludeWorldwide.SetTo(paramsDotExcludeWorldwideVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "exclude_worldwide",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: seniority.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "seniority",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSeniorityVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSeniorityVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Seniority.SetTo(paramsDotSeniorityVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "seniority",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: employment_type.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "employment_type",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotEmploymentTypeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotEmploymentTypeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.EmploymentType.SetTo(paramsDotEmploymentTypeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "employment_type",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: company.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "company",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCompanyVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCompanyVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Company.SetTo(paramsDotCompanyVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "company",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: timezone.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "timezone",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTimezoneVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTimezoneVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Timezone.SetTo(paramsDotTimezoneVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "timezone",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: sort.
	{
		val := SearchJobsSort("relevant")
		params.Sort.SetTo(val)
	}
	// Decode query: sort.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sort",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSortVal SearchJobsSort
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSortVal = SearchJobsSort(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Sort.SetTo(paramsDotSortVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Sort.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sort",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: page.
	{
		val := int(1)
		params.Page.SetTo(val)
	}
	// Decode query: page.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "page",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPageVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotPageVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Page.SetTo(paramsDotPageVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Page.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "page",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
