// Code generated by ogen, DO NOT EDIT.

package himalayas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// BrowseJobs implements browseJobs operation.
//
// Returns the full unfiltered remote jobs feed with offset/limit pagination. `limit` values above 20
// are clamped to 20 server-side (no 400, despite the official document).
//
// GET /jobs/api
func (UnimplementedHandler) BrowseJobs(ctx context.Context, params BrowseJobsParams) (r *JobsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchJobs implements searchJobs operation.
//
// Returns filtered remote job results in the same JSON shape as `GET /jobs/api`, paginated by 1-based
// `page` (fixed 20 per page; the response echoes the equivalent offset). A returned page may hold
// fewer than 20 jobs even when more pages remain — paginate by totalCount, not page fullness.
//
// GET /jobs/api/search
func (UnimplementedHandler) SearchJobs(ctx context.Context, params SearchJobsParams) (r SearchJobsRes, _ error) {
	return r, ht.ErrNotImplemented
}
