// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetJobDetailOperation   OperationName = "GetJobDetail"
	InitSessionOperation    OperationName = "InitSession"
	PostSearchJobsOperation OperationName = "PostSearchJobs"
)
