// Code generated by ogen, DO NOT EDIT.

package greenhouse

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetJob implements getJob operation.
//
// Retrieve a single job.
//
// GET /boards/{board_token}/jobs/{job_id}
func (UnimplementedHandler) GetJob(ctx context.Context, params GetJobParams) (r GetJobRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListJobs implements listJobs operation.
//
// List all jobs for a board.
//
// GET /boards/{board_token}/jobs
func (UnimplementedHandler) ListJobs(ctx context.Context, params ListJobsParams) (r ListJobsRes, _ error) {
	return r, ht.ErrNotImplemented
}
