// Code generated by ogen, DO NOT EDIT.

package greenhouse

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetJobParams is parameters of getJob operation.
type GetJobParams struct {
	BoardToken string
	// ID of the job to retrieve (the posting `id`, not `internal_job_id`).
	JobID int
	// If true, includes questions, location_questions, data_compliance, and demographic_questions
	// (application form structure).
	Questions OptBool `json:",omitempty,omitzero"`
	// If true, includes the pay_input_ranges array.
	PayTransparency OptBool `json:",omitempty,omitzero"`
}

func unpackGetJobParams(packed middleware.Parameters) (params GetJobParams) {
	{
		key := middleware.ParameterKey{
			Name: "board_token",
			In:   "path",
		}
		params.BoardToken = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "job_id",
			In:   "path",
		}
		params.JobID = packed[key].(int)
	}
	{
		key := middleware.ParameterKey{
			Name: "questions",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Questions = v.(OptBool)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "pay_transparency",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.PayTransparency = v.(OptBool)
		}
	}
	return params
}

func decodeGetJobParams(args [2]string, argsEscaped bool, r *http.Request) (params GetJobParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: board_token.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "board_token",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.BoardToken = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "board_token",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: job_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "job_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.JobID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "job_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: questions.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "questions",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotQuestionsVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotQuestionsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Questions.SetTo(paramsDotQuestionsVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "questions",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: pay_transparency.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "pay_transparency",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPayTransparencyVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotPayTransparencyVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.PayTransparency.SetTo(paramsDotPayTransparencyVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "pay_transparency",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListJobsParams is parameters of listJobs operation.
type ListJobsParams struct {
	// Job Board URL token (e.g. "acme" in boards.greenhouse.io/acme).
	BoardToken string
	// If true, includes the full post description (content), departments, and offices for each job.
	Content OptBool `json:",omitempty,omitzero"`
}

func unpackListJobsParams(packed middleware.Parameters) (params ListJobsParams) {
	{
		key := middleware.ParameterKey{
			Name: "board_token",
			In:   "path",
		}
		params.BoardToken = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "content",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Content = v.(OptBool)
		}
	}
	return params
}

func decodeListJobsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListJobsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: board_token.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "board_token",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.BoardToken = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "board_token",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: content.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "content",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotContentVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotContentVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Content.SetTo(paramsDotContentVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "content",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
