// Code generated by ogen, DO NOT EDIT.

package greenhouse

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetJob implements getJob operation.
	//
	// Retrieve a single job.
	//
	// GET /boards/{board_token}/jobs/{job_id}
	GetJob(ctx context.Context, params GetJobParams) (GetJobRes, error)
	// ListJobs implements listJobs operation.
	//
	// List all jobs for a board.
	//
	// GET /boards/{board_token}/jobs
	ListJobs(ctx context.Context, params ListJobsParams) (ListJobsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
