// Code generated by ogen, DO NOT EDIT.

package amazon

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// SearchJobsParams is parameters of searchJobs operation.
type SearchJobsParams struct {
	// Free-text query, or a numeric id_icims for detail lookup.
	BaseQuery OptString `json:",omitempty,omitzero"`
	// ISO 3166-1 alpha-3 country codes, OR'd together.
	NormalizedCountryCode []string `json:",omitempty"`
	// Normalized city names, OR'd together.
	NormalizedCityName []string `json:",omitempty"`
	// Job category display names, OR'd together.
	Category []string `json:",omitempty"`
	// Business-category slugs, OR'd together.
	BusinessCategory []string `json:",omitempty"`
	// Schedule type display values, OR'd together.
	ScheduleTypeID []string `json:",omitempty"`
	// Result ordering. The upstream defaults to relevance.
	Sort OptSearchJobsSort `json:",omitempty,omitzero"`
	// Zero-based result offset.
	Offset OptInt `json:",omitempty,omitzero"`
	// Page size. Values above 100 produce a soft error payload.
	ResultLimit OptInt `json:",omitempty,omitzero"`
}

func unpackSearchJobsParams(packed middleware.Parameters) (params SearchJobsParams) {
	{
		key := middleware.ParameterKey{
			Name: "base_query",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.BaseQuery = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "normalized_country_code[]",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.NormalizedCountryCode = v.([]string)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "normalized_city_name[]",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.NormalizedCityName = v.([]string)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "category[]",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Category = v.([]string)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "business_category[]",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.BusinessCategory = v.([]string)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "schedule_type_id[]",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ScheduleTypeID = v.([]string)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "sort",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Sort = v.(OptSearchJobsSort)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "result_limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ResultLimit = v.(OptInt)
		}
	}
	return params
}

func decodeSearchJobsParams(args [0]string, argsEscaped bool, r *http.Request) (params SearchJobsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: base_query.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "base_query",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotBaseQueryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotBaseQueryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.BaseQuery.SetTo(paramsDotBaseQueryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "base_query",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: normalized_country_code[].
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "normalized_country_code[]",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				params.NormalizedCountryCode = nil
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotNormalizedCountryCodeVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotNormalizedCountryCodeVal = c
						return nil
					}(); err != nil {
						return err
					}
					params.NormalizedCountryCode = append(params.NormalizedCountryCode, paramsDotNormalizedCountryCodeVal)
					return nil
				})
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "normalized_country_code[]",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: normalized_city_name[].
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "normalized_city_name[]",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				params.NormalizedCityName = nil
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotNormalizedCityNameVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotNormalizedCityNameVal = c
						return nil
					}(); err != nil {
						return err
					}
					params.NormalizedCityName = append(params.NormalizedCityName, paramsDotNormalizedCityNameVal)
					return nil
				})
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "normalized_city_name[]",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: category[].
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "category[]",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				params.Category = nil
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotCategoryVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotCategoryVal = c
						return nil
					}(); err != nil {
						return err
					}
					params.Category = append(params.Category, paramsDotCategoryVal)
					return nil
				})
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "category[]",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: business_category[].
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "business_category[]",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				params.BusinessCategory = nil
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotBusinessCategoryVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotBusinessCategoryVal = c
						return nil
					}(); err != nil {
						return err
					}
					params.BusinessCategory = append(params.BusinessCategory, paramsDotBusinessCategoryVal)
					return nil
				})
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "business_category[]",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: schedule_type_id[].
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "schedule_type_id[]",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				params.ScheduleTypeID = nil
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotScheduleTypeIDVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotScheduleTypeIDVal = c
						return nil
					}(); err != nil {
						return err
					}
					params.ScheduleTypeID = append(params.ScheduleTypeID, paramsDotScheduleTypeIDVal)
					return nil
				})
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "schedule_type_id[]",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: sort.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sort",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSortVal SearchJobsSort
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSortVal = SearchJobsSort(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Sort.SetTo(paramsDotSortVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Sort.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sort",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Offset.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: result_limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "result_limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotResultLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotResultLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ResultLimit.SetTo(paramsDotResultLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.ResultLimit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "result_limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
