// Code generated by ogen, DO NOT EDIT.

package amazon

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// SearchJobs implements searchJobs operation.
	//
	// Searches jobs using server-side filters and zero-based offset pagination. All parameters are
	// optional upstream. Array filters are encoded as repeated query parameters whose names end in `[]`.
	//
	// GET /en/search.json
	SearchJobs(ctx context.Context, params SearchJobsParams) (*SearchResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
