// Code generated by ogen, DO NOT EDIT.

package amazon

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// SearchJobs implements searchJobs operation.
//
// Searches jobs using server-side filters and zero-based offset pagination. All parameters are
// optional upstream. Array filters are encoded as repeated query parameters whose names end in `[]`.
//
// GET /en/search.json
func (UnimplementedHandler) SearchJobs(ctx context.Context, params SearchJobsParams) (r *SearchResponse, _ error) {
	return r, ht.ErrNotImplemented
}
