// Code generated by ogen, DO NOT EDIT.

package amazon

import (
	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s SearchJobsSort) Validate() error {
	switch s {
	case "relevant":
		return nil
	case "recent":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SearchResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.Int{
			MinSet:        true,
			Min:           0,
			MaxSet:        false,
			Max:           0,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    0,
			Pattern:       nil,
		}).Validate(int64(s.Hits)); err != nil {
			return errors.Wrap(err, "int")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "hits",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Jobs.Get(); ok {
			if err := func() error {
				if value == nil {
					return errors.New("nil is invalid value")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "jobs",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}
