// Code generated by ogen, DO NOT EDIT.

package amazon

import (
	"net/url"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/Job
type Job struct {
	// Opaque internal UUID; not the public MCP job id.
	ID string `json:"id"`
	// Numeric public posting id used in job_path and lookup.
	IDIcims string `json:"id_icims"`
	Title   string `json:"title"`
	// Display location, such as `TW, TPE, Taipei`.
	Location string `json:"location"`
	// Normalized city, region, and country.
	NormalizedLocation string `json:"normalized_location"`
	City               string `json:"city"`
	// ISO 3166-1 alpha-3 country code.
	CountryCode string `json:"country_code"`
	// Amazon legal employing entity.
	CompanyName string `json:"company_name"`
	// Public path beginning with `/en/jobs/{id_icims}/`.
	JobPath string `json:"job_path"`
	// Human-readable publication date supplied by Amazon.
	PostedDate string `json:"posted_date"`
	// Human-readable age of the latest update.
	UpdatedTime string `json:"updated_time"`
	// Plain-text preview from the search index.
	DescriptionShort string `json:"description_short"`
	// Full HTML-fragment job description.
	Description string `json:"description"`
	// Required qualifications as an HTML fragment.
	BasicQualifications string `json:"basic_qualifications"`
	// Preferred qualifications as an HTML fragment.
	PreferredQualifications string `json:"preferred_qualifications"`
	JobCategory             string `json:"job_category"`
	// Amazon business-category slug.
	BusinessCategory string `json:"business_category"`
	// Normalized schedule type, such as `full-time`.
	JobScheduleType string `json:"job_schedule_type"`
	// Application URL.
	URLNextStep url.URL `json:"url_next_step"`
}

// GetID returns the value of ID.
func (s *Job) GetID() string {
	return s.ID
}

// GetIDIcims returns the value of IDIcims.
func (s *Job) GetIDIcims() string {
	return s.IDIcims
}

// GetTitle returns the value of Title.
func (s *Job) GetTitle() string {
	return s.Title
}

// GetLocation returns the value of Location.
func (s *Job) GetLocation() string {
	return s.Location
}

// GetNormalizedLocation returns the value of NormalizedLocation.
func (s *Job) GetNormalizedLocation() string {
	return s.NormalizedLocation
}

// GetCity returns the value of City.
func (s *Job) GetCity() string {
	return s.City
}

// GetCountryCode returns the value of CountryCode.
func (s *Job) GetCountryCode() string {
	return s.CountryCode
}

// GetCompanyName returns the value of CompanyName.
func (s *Job) GetCompanyName() string {
	return s.CompanyName
}

// GetJobPath returns the value of JobPath.
func (s *Job) GetJobPath() string {
	return s.JobPath
}

// GetPostedDate returns the value of PostedDate.
func (s *Job) GetPostedDate() string {
	return s.PostedDate
}

// GetUpdatedTime returns the value of UpdatedTime.
func (s *Job) GetUpdatedTime() string {
	return s.UpdatedTime
}

// GetDescriptionShort returns the value of DescriptionShort.
func (s *Job) GetDescriptionShort() string {
	return s.DescriptionShort
}

// GetDescription returns the value of Description.
func (s *Job) GetDescription() string {
	return s.Description
}

// GetBasicQualifications returns the value of BasicQualifications.
func (s *Job) GetBasicQualifications() string {
	return s.BasicQualifications
}

// GetPreferredQualifications returns the value of PreferredQualifications.
func (s *Job) GetPreferredQualifications() string {
	return s.PreferredQualifications
}

// GetJobCategory returns the value of JobCategory.
func (s *Job) GetJobCategory() string {
	return s.JobCategory
}

// GetBusinessCategory returns the value of BusinessCategory.
func (s *Job) GetBusinessCategory() string {
	return s.BusinessCategory
}

// GetJobScheduleType returns the value of JobScheduleType.
func (s *Job) GetJobScheduleType() string {
	return s.JobScheduleType
}

// GetURLNextStep returns the value of URLNextStep.
func (s *Job) GetURLNextStep() url.URL {
	return s.URLNextStep
}

// SetID sets the value of ID.
func (s *Job) SetID(val string) {
	s.ID = val
}

// SetIDIcims sets the value of IDIcims.
func (s *Job) SetIDIcims(val string) {
	s.IDIcims = val
}

// SetTitle sets the value of Title.
func (s *Job) SetTitle(val string) {
	s.Title = val
}

// SetLocation sets the value of Location.
func (s *Job) SetLocation(val string) {
	s.Location = val
}

// SetNormalizedLocation sets the value of NormalizedLocation.
func (s *Job) SetNormalizedLocation(val string) {
	s.NormalizedLocation = val
}

// SetCity sets the value of City.
func (s *Job) SetCity(val string) {
	s.City = val
}

// SetCountryCode sets the value of CountryCode.
func (s *Job) SetCountryCode(val string) {
	s.CountryCode = val
}

// SetCompanyName sets the value of CompanyName.
func (s *Job) SetCompanyName(val string) {
	s.CompanyName = val
}

// SetJobPath sets the value of JobPath.
func (s *Job) SetJobPath(val string) {
	s.JobPath = val
}

// SetPostedDate sets the value of PostedDate.
func (s *Job) SetPostedDate(val string) {
	s.PostedDate = val
}

// SetUpdatedTime sets the value of UpdatedTime.
func (s *Job) SetUpdatedTime(val string) {
	s.UpdatedTime = val
}

// SetDescriptionShort sets the value of DescriptionShort.
func (s *Job) SetDescriptionShort(val string) {
	s.DescriptionShort = val
}

// SetDescription sets the value of Description.
func (s *Job) SetDescription(val string) {
	s.Description = val
}

// SetBasicQualifications sets the value of BasicQualifications.
func (s *Job) SetBasicQualifications(val string) {
	s.BasicQualifications = val
}

// SetPreferredQualifications sets the value of PreferredQualifications.
func (s *Job) SetPreferredQualifications(val string) {
	s.PreferredQualifications = val
}

// SetJobCategory sets the value of JobCategory.
func (s *Job) SetJobCategory(val string) {
	s.JobCategory = val
}

// SetBusinessCategory sets the value of BusinessCategory.
func (s *Job) SetBusinessCategory(val string) {
	s.BusinessCategory = val
}

// SetJobScheduleType sets the value of JobScheduleType.
func (s *Job) SetJobScheduleType(val string) {
	s.JobScheduleType = val
}

// SetURLNextStep sets the value of URLNextStep.
func (s *Job) SetURLNextStep(val url.URL) {
	s.URLNextStep = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilJobArray returns new OptNilJobArray with value set to v.
func NewOptNilJobArray(v []Job) OptNilJobArray {
	return OptNilJobArray{
		Value: v,
		Set:   true,
	}
}

// OptNilJobArray is optional nullable []Job.
type OptNilJobArray struct {
	Value []Job
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilJobArray was set.
func (o OptNilJobArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilJobArray) Reset() {
	var v []Job
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilJobArray) SetTo(v []Job) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilJobArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilJobArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []Job
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilJobArray) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilJobArray) Get() (v []Job, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilJobArray) Or(d []Job) []Job {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSearchJobsSort returns new OptSearchJobsSort with value set to v.
func NewOptSearchJobsSort(v SearchJobsSort) OptSearchJobsSort {
	return OptSearchJobsSort{
		Value: v,
		Set:   true,
	}
}

// OptSearchJobsSort is optional SearchJobsSort.
type OptSearchJobsSort struct {
	Value SearchJobsSort
	Set   bool
}

// IsSet returns true if OptSearchJobsSort was set.
func (o OptSearchJobsSort) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSearchJobsSort) Reset() {
	var v SearchJobsSort
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSearchJobsSort) SetTo(v SearchJobsSort) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSearchJobsSort) Get() (v SearchJobsSort, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSearchJobsSort) Or(d SearchJobsSort) SearchJobsSort {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type SearchJobsSort string

const (
	SearchJobsSortRelevant SearchJobsSort = "relevant"
	SearchJobsSortRecent   SearchJobsSort = "recent"
)

// AllValues returns all SearchJobsSort values.
func (SearchJobsSort) AllValues() []SearchJobsSort {
	return []SearchJobsSort{
		SearchJobsSortRelevant,
		SearchJobsSortRecent,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SearchJobsSort) MarshalText() ([]byte, error) {
	switch s {
	case SearchJobsSortRelevant:
		return []byte(s), nil
	case SearchJobsSortRecent:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SearchJobsSort) UnmarshalText(data []byte) error {
	switch SearchJobsSort(data) {
	case SearchJobsSortRelevant:
		*s = SearchJobsSortRelevant
		return nil
	case SearchJobsSortRecent:
		*s = SearchJobsSortRecent
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SearchResponse
type SearchResponse struct {
	// Upstream validation error; null on a successful search.
	Error OptNilString `json:"error"`
	// Total number of matching jobs.
	Hits int `json:"hits"`
	// Current page of jobs. Null only when `error` reports a soft validation failure.
	Jobs OptNilJobArray `json:"jobs"`
}

// GetError returns the value of Error.
func (s *SearchResponse) GetError() OptNilString {
	return s.Error
}

// GetHits returns the value of Hits.
func (s *SearchResponse) GetHits() int {
	return s.Hits
}

// GetJobs returns the value of Jobs.
func (s *SearchResponse) GetJobs() OptNilJobArray {
	return s.Jobs
}

// SetError sets the value of Error.
func (s *SearchResponse) SetError(val OptNilString) {
	s.Error = val
}

// SetHits sets the value of Hits.
func (s *SearchResponse) SetHits(val int) {
	s.Hits = val
}

// SetJobs sets the value of Jobs.
func (s *SearchResponse) SetJobs(val OptNilJobArray) {
	s.Jobs = val
}
