name: Hurl live test

on:
  schedule:
    # 10:00 Asia/Taipei (UTC+8) daily
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  hurl-test:
    runs-on: ubuntu-latest
    env:
      HURL_VERSION: 8.0.1
    steps:
      - uses: actions/checkout@v5

      - name: Install hurl
        run: |
          curl --location --remote-name "https://github.com/Orange-OpenSource/hurl/releases/download/${HURL_VERSION}/hurl_${HURL_VERSION}_amd64.deb"
          sudo apt update && sudo apt install ./hurl_${HURL_VERSION}_amd64.deb

      - name: Run live requests
        run: make hurl-test
