// Code generated by ogen, DO NOT EDIT.

package workday

// OperationName is the ogen operation name
type OperationName = string

const (
	GetJobDetailOperation OperationName = "GetJobDetail"
	SearchJobsOperation   OperationName = "SearchJobs"
)
